// Code generated by ohm-cli generate types. Using gotmpl - DO NOT EDIT.
/* ohm-cli generate go \
--grammar-name ES5 \
--hand-coded-walk \
--skip-type-check-method \
--output-dir es5
*/
package es5

import (
	"github.com/ohmjs/ohm-go/ohm"
)

// types for grammar ES5

// Program
// -- rule --
// Program = &(Directive*) SourceElement*
// ----
type Program[P, R any] struct {
	SourceElement ohm.ListNode
}

// sourceCharacter
// -- rule --
// sourceCharacter = any
// ----
type LexSourceCharacter[P, R any] struct {
	Any ohm.RuleNode
}

// space
// -- rule --
// space := whitespace | lineTerminator | comment
// ----
type LexSpace[P, R any] struct {
	Rule ohm.RuleNode
}

// whitespace
// -- rule --
// whitespace = "\t"
// | "\x0B"    -- verticalTab
// | "\x0C"    -- formFeed
// | " "
// | "\u00A0"  -- noBreakSpace
// | "\uFEFF"  -- byteOrderMark
// | unicodeSpaceSeparator
// ----
type LexWhitespace[P, R any] struct {
	Node ohm.Node
}

// whitespace_verticalTab
// -- rule --
// "\x0B"
// ----
type LexWhitespaceVerticalTab[P, R any] struct {
	Term ohm.TerminalNode
}

// whitespace_formFeed
// -- rule --
// "\x0C"
// ----
type LexWhitespaceFormFeed[P, R any] struct {
	Term ohm.TerminalNode
}

// whitespace_noBreakSpace
// -- rule --
// "\u00A0"
// ----
type LexWhitespaceNoBreakSpace[P, R any] struct {
	Term ohm.TerminalNode
}

// whitespace_byteOrderMark
// -- rule --
// "\uFEFF"
// ----
type LexWhitespaceByteOrderMark[P, R any] struct {
	Term ohm.TerminalNode
}

// lineTerminator
// -- rule --
// lineTerminator = "\n" | "\r" | "\u2028" | "\u2029"
// ----
type LexLineTerminator[P, R any] struct {
	Term ohm.TerminalNode
}

// lineTerminatorSequence
// -- rule --
// lineTerminatorSequence = "\n" | "\r" ~"\n" | "\u2028" | "\u2029" | "\r\n"
// ----
type LexLineTerminatorSequence[P, R any] struct {
	Term ohm.TerminalNode
}

// comment
// -- rule --
// comment = multiLineComment | singleLineComment
// ----
type LexComment[P, R any] struct {
	Rule ohm.RuleNode
}

// multiLineComment
// -- rule --
// multiLineComment = "/*" (~"*/" sourceCharacter)* "*/"
// ----
type LexMultiLineComment[P, R any] struct {
	Term1 ohm.TerminalNode
	Alt   ohm.ListNode
	Term2 ohm.TerminalNode
}

// singleLineComment
// -- rule --
// singleLineComment = "//" (~lineTerminator sourceCharacter)*
// ----
type LexSingleLineComment[P, R any] struct {
	Term ohm.TerminalNode
	Alt  ohm.ListNode
}

// identifier - an identifier
// -- rule --
// identifier (an identifier) = ~reservedWord identifierName
// ----
type LexIdentifier[P, R any] struct {
	IdentifierName ohm.RuleNode
}

// identifierName
// -- rule --
// identifierName = identifierStart identifierPart*
// ----
type LexIdentifierName[P, R any] struct {
	IdentifierStart ohm.RuleNode
	IdentifierPart  ohm.ListNode
}

// identifierStart
// -- rule --
// identifierStart = letter | "$" | "_"
// | "\\" unicodeEscapeSequence -- escaped
//
// ----
type LexIdentifierStart[P, R any] struct {
	Node ohm.Node
}

// identifierStart_escaped
// -- rule --
// "\\" unicodeEscapeSequence
// ----
type LexIdentifierStartEscaped[P, R any] struct {
	Term                  ohm.TerminalNode
	UnicodeEscapeSequence ohm.RuleNode
}

// identifierPart
// -- rule --
// identifierPart = identifierStart | unicodeCombiningMark
// | unicodeDigit | unicodeConnectorPunctuation
// | "\u200C" | "\u200D"
// ----
type LexIdentifierPart[P, R any] struct {
	Arg1 ohm.Node
}

// letter
// -- rule --
// letter += unicodeCategoryNl
// ----
type LexLetter[P, R any] struct {
	UnicodeCategoryNl ohm.RuleNode
}

// unicodeCategoryNl
// -- rule --
// unicodeCategoryNl
// = "\u2160".."\u2182" | "\u3007" | "\u3021".."\u3029"
// ----
type LexUnicodeCategoryNl[P, R any] struct {
	Arg1 ohm.Node
}

// unicodeDigit - a digit
// -- rule --
// unicodeDigit (a digit)
// = "\u0030".."\u0039" | "\u0660".."\u0669" | "\u06F0".."\u06F9" | "\u0966".."\u096F" | "\u09E6".."\u09EF" | "\u0A66".."\u0A6F" | "\u0AE6".."\u0AEF" | "\u0B66".."\u0B6F" | "\u0BE7".."\u0BEF" | "\u0C66".."\u0C6F" | "\u0CE6".."\u0CEF" | "\u0D66".."\u0D6F" | "\u0E50".."\u0E59" | "\u0ED0".."\u0ED9" | "\u0F20".."\u0F29" | "\uFF10".."\uFF19"
// ----
type LexUnicodeDigit[P, R any] struct {
	Rng ohm.TerminalNode
}

// unicodeCombiningMark - a Unicode combining mark
// -- rule --
// unicodeCombiningMark (a Unicode combining mark)
// = "\u0300".."\u0345" | "\u0360".."\u0361" | "\u0483".."\u0486" | "\u0591".."\u05A1" | "\u05A3".."\u05B9" | "\u05BB".."\u05BD" | "\u05BF".."\u05BF" | "\u05C1".."\u05C2" | "\u05C4".."\u05C4" | "\u064B".."\u0652" | "\u0670".."\u0670" | "\u06D6".."\u06DC" | "\u06DF".."\u06E4" | "\u06E7".."\u06E8" | "\u06EA".."\u06ED" | "\u0901".."\u0902" | "\u093C".."\u093C" | "\u0941".."\u0948" | "\u094D".."\u094D" | "\u0951".."\u0954" | "\u0962".."\u0963" | "\u0981".."\u0981" | "\u09BC".."\u09BC" | "\u09C1".."\u09C4" | "\u09CD".."\u09CD" | "\u09E2".."\u09E3" | "\u0A02".."\u0A02" | "\u0A3C".."\u0A3C" | "\u0A41".."\u0A42" | "\u0A47".."\u0A48" | "\u0A4B".."\u0A4D" | "\u0A70".."\u0A71" | "\u0A81".."\u0A82" | "\u0ABC".."\u0ABC" | "\u0AC1".."\u0AC5" | "\u0AC7".."\u0AC8" | "\u0ACD".."\u0ACD" | "\u0B01".."\u0B01" | "\u0B3C".."\u0B3C" | "\u0B3F".."\u0B3F" | "\u0B41".."\u0B43" | "\u0B4D".."\u0B4D" | "\u0B56".."\u0B56" | "\u0B82".."\u0B82" | "\u0BC0".."\u0BC0" | "\u0BCD".."\u0BCD" | "\u0C3E".."\u0C40" | "\u0C46".."\u0C48" | "\u0C4A".."\u0C4D" | "\u0C55".."\u0C56" | "\u0CBF".."\u0CBF" | "\u0CC6".."\u0CC6" | "\u0CCC".."\u0CCD" | "\u0D41".."\u0D43" | "\u0D4D".."\u0D4D" | "\u0E31".."\u0E31" | "\u0E34".."\u0E3A" | "\u0E47".."\u0E4E" | "\u0EB1".."\u0EB1" | "\u0EB4".."\u0EB9" | "\u0EBB".."\u0EBC" | "\u0EC8".."\u0ECD" | "\u0F18".."\u0F19" | "\u0F35".."\u0F35" | "\u0F37".."\u0F37" | "\u0F39".."\u0F39" | "\u0F71".."\u0F7E" | "\u0F80".."\u0F84" | "\u0F86".."\u0F87" | "\u0F90".."\u0F95" | "\u0F97".."\u0F97" | "\u0F99".."\u0FAD" | "\u0FB1".."\u0FB7" | "\u0FB9".."\u0FB9" | "\u20D0".."\u20DC" | "\u20E1".."\u20E1" | "\u302A".."\u302F" | "\u3099".."\u309A" | "\uFB1E".."\uFB1E" | "\uFE20".."\uFE23"
// ----
type LexUnicodeCombiningMark[P, R any] struct {
	Rng ohm.TerminalNode
}

// unicodeConnectorPunctuation
// -- rule --
// unicodeConnectorPunctuation = "\u005F" | "\u203F".."\u2040" | "\u30FB" | "\uFE33".."\uFE34" | "\uFE4D".."\uFE4F" | "\uFF3F" | "\uFF65"
// ----
type LexUnicodeConnectorPunctuation[P, R any] struct {
	Arg1 ohm.Node
}

// unicodeSpaceSeparator
// -- rule --
// unicodeSpaceSeparator = "\u2000".."\u200B" | "\u3000"
// ----
type LexUnicodeSpaceSeparator[P, R any] struct {
	Arg ohm.Node
}

// reservedWord
// -- rule --
// reservedWord = keyword | futureReservedWord | nullLiteral | booleanLiteral
// ----
type LexReservedWord[P, R any] struct {
	Rule ohm.RuleNode
}

// keyword
// -- rule --
// keyword = break    | do        | instanceof | typeof
// | case     | else      | new        | var
// | catch    | finally   | return     | void
// | continue | for       | switch     | while
// | debugger | function  | this       | with
// | default  | if        | throw
// | delete   | in        | try
// ----
type LexKeyword[P, R any] struct {
	Rule ohm.RuleNode
}

// futureReservedWordLax
// -- rule --
// futureReservedWordLax = class  | enum  | extends
// | super  | const | export
// | import
// ----
type LexFutureReservedWordLax[P, R any] struct {
	Rule ohm.RuleNode
}

// futureReservedWordStrict
// -- rule --
// futureReservedWordStrict = futureReservedWordLax
// | implements | let     | private   | public
// | interface  | package | protected | static
// | yield
// ----
type LexFutureReservedWordStrict[P, R any] struct {
	Rule ohm.RuleNode
}

// futureReservedWord
// -- rule --
// futureReservedWord = futureReservedWordStrict
// ----
type LexFutureReservedWord[P, R any] struct {
	FutureReservedWordStrict ohm.RuleNode
}

// literal
// -- rule --
// literal = nullLiteral | booleanLiteral | numericLiteral
// | stringLiteral | regularExpressionLiteral
// ----
type LexLiteral[P, R any] struct {
	Rule ohm.RuleNode
}

// nullLiteral
// -- rule --
// nullLiteral = "null" ~identifierPart
// ----
type LexNullLiteral[P, R any] struct {
	Term ohm.TerminalNode
}

// booleanLiteral
// -- rule --
// booleanLiteral = ("true" | "false") ~identifierPart
// ----
type LexBooleanLiteral[P, R any] struct {
	Alt ohm.Node
}

// numericLiteral
// -- rule --
// numericLiteral = octalIntegerLiteral | hexIntegerLiteral | decimalLiteral
// ----
type LexNumericLiteral[P, R any] struct {
	Rule ohm.RuleNode
}

// decimalLiteral
// -- rule --
// decimalLiteral = decimalIntegerLiteral "." decimalDigit* exponentPart -- bothParts
// |                       "." decimalDigit+ exponentPart -- decimalsOnly
// | decimalIntegerLiteral                   exponentPart -- integerOnly
//
// ----
type LexDecimalLiteral[P, R any] struct {
	Node ohm.Node
}

// decimalLiteral_bothParts
// -- rule --
// decimalIntegerLiteral "." decimalDigit* exponentPart
// ----
type LexDecimalLiteralBothParts[P, R any] struct {
	DecimalIntegerLiteral ohm.RuleNode
	Term                  ohm.TerminalNode
	DecimalDigit          ohm.ListNode
	ExponentPart          ohm.RuleNode
}

// decimalLiteral_decimalsOnly
// -- rule --
// "." decimalDigit+ exponentPart
// ----
type LexDecimalLiteralDecimalsOnly[P, R any] struct {
	Term         ohm.TerminalNode
	DecimalDigit ohm.ListNode
	ExponentPart ohm.RuleNode
}

// decimalLiteral_integerOnly
// -- rule --
// decimalIntegerLiteral                   exponentPart
// ----
type LexDecimalLiteralIntegerOnly[P, R any] struct {
	DecimalIntegerLiteral ohm.RuleNode
	ExponentPart          ohm.RuleNode
}

// decimalIntegerLiteral
// -- rule --
// decimalIntegerLiteral = nonZeroDigit decimalDigit*  -- nonZero
// | "0"                         -- zero
//
// ----
type LexDecimalIntegerLiteral[P, R any] struct {
	Node ohm.Node
}

// decimalIntegerLiteral_nonZero
// -- rule --
// nonZeroDigit decimalDigit*
// ----
type LexDecimalIntegerLiteralNonZero[P, R any] struct {
	NonZeroDigit ohm.RuleNode
	DecimalDigit ohm.ListNode
}

// decimalIntegerLiteral_zero
// -- rule --
// "0"
// ----
type LexDecimalIntegerLiteralZero[P, R any] struct {
	Term ohm.TerminalNode
}

// decimalDigit
// -- rule --
// decimalDigit = "0".."9"
// ----
type LexDecimalDigit[P, R any] struct {
	Rng ohm.TerminalNode
}

// nonZeroDigit
// -- rule --
// nonZeroDigit = "1".."9"
// ----
type LexNonZeroDigit[P, R any] struct {
	Rng ohm.TerminalNode
}

// exponentPart
// -- rule --
// exponentPart = exponentIndicator signedInteger -- present
// |                                 -- absent
//
// ----
type LexExponentPart[P, R any] struct {
	Node ohm.Node
}

// exponentPart_present
// -- rule --
// exponentIndicator signedInteger
// ----
type LexExponentPartPresent[P, R any] struct {
	ExponentIndicator ohm.RuleNode
	SignedInteger     ohm.RuleNode
}

// exponentPart_absent
// -- rule --
//
// ----
type LexExponentPartAbsent[P, R any] struct {
}

// exponentIndicator
// -- rule --
// exponentIndicator = "e" | "E"
// ----
type LexExponentIndicator[P, R any] struct {
	Term ohm.TerminalNode
}

// signedInteger
// -- rule --
// signedInteger = "+" decimalDigit* -- positive
// | "-" decimalDigit* -- negative
// |     decimalDigit+ -- noSign
//
// ----
type LexSignedInteger[P, R any] struct {
	Node ohm.Node
}

// signedInteger_positive
// -- rule --
// "+" decimalDigit*
// ----
type LexSignedIntegerPositive[P, R any] struct {
	Term         ohm.TerminalNode
	DecimalDigit ohm.ListNode
}

// signedInteger_negative
// -- rule --
// "-" decimalDigit*
// ----
type LexSignedIntegerNegative[P, R any] struct {
	Term         ohm.TerminalNode
	DecimalDigit ohm.ListNode
}

// signedInteger_noSign
// -- rule --
// decimalDigit+
// ----
type LexSignedIntegerNoSign[P, R any] struct {
	DecimalDigit ohm.ListNode
}

// hexIntegerLiteral
// -- rule --
// hexIntegerLiteral = "0x" hexDigit+
// | "0X" hexDigit+
// ----
type LexHexIntegerLiteral[P, R any] struct {
	Term     ohm.TerminalNode
	HexDigit ohm.ListNode
}

// octalIntegerLiteral
// -- rule --
// octalIntegerLiteral = "0" octalDigit+
// ----
type LexOctalIntegerLiteral[P, R any] struct {
	Term       ohm.TerminalNode
	OctalDigit ohm.ListNode
}

// octalDigit
// -- rule --
// octalDigit = "0".."7"
// ----
type LexOctalDigit[P, R any] struct {
	Rng ohm.TerminalNode
}

// stringLiteral
// -- rule --
// stringLiteral = "\"" doubleStringCharacter* "\""
// | "'" singleStringCharacter* "'"
// ----
type LexStringLiteral[P, R any] struct {
	Term1 ohm.TerminalNode
	Arg   ohm.Node
	Term2 ohm.TerminalNode
}

// doubleStringCharacter
// -- rule --
// doubleStringCharacter = ~("\"" | "\\" | lineTerminator) sourceCharacter -- nonEscaped
// | "\\" escapeSequence                             -- escaped
// | lineContinuation                                -- lineContinuation
//
// ----
type LexDoubleStringCharacter[P, R any] struct {
	Node ohm.Node
}

// doubleStringCharacter_nonEscaped
// -- rule --
// ~("\"" | "\\" | lineTerminator) sourceCharacter
// ----
type LexDoubleStringCharacterNonEscaped[P, R any] struct {
	SourceCharacter ohm.RuleNode
}

// doubleStringCharacter_escaped
// -- rule --
// "\\" escapeSequence
// ----
type LexDoubleStringCharacterEscaped[P, R any] struct {
	Term           ohm.TerminalNode
	EscapeSequence ohm.RuleNode
}

// doubleStringCharacter_lineContinuation
// -- rule --
// lineContinuation
// ----
type LexDoubleStringCharacterLineContinuation[P, R any] struct {
	LineContinuation ohm.RuleNode
}

// singleStringCharacter
// -- rule --
// singleStringCharacter = ~("'" | "\\" | lineTerminator) sourceCharacter -- nonEscaped
// | "\\" escapeSequence                            -- escaped
// | lineContinuation                               -- lineContinuation
//
// ----
type LexSingleStringCharacter[P, R any] struct {
	Node ohm.Node
}

// singleStringCharacter_nonEscaped
// -- rule --
// ~("'" | "\\" | lineTerminator) sourceCharacter
// ----
type LexSingleStringCharacterNonEscaped[P, R any] struct {
	SourceCharacter ohm.RuleNode
}

// singleStringCharacter_escaped
// -- rule --
// "\\" escapeSequence
// ----
type LexSingleStringCharacterEscaped[P, R any] struct {
	Term           ohm.TerminalNode
	EscapeSequence ohm.RuleNode
}

// singleStringCharacter_lineContinuation
// -- rule --
// lineContinuation
// ----
type LexSingleStringCharacterLineContinuation[P, R any] struct {
	LineContinuation ohm.RuleNode
}

// lineContinuation
// -- rule --
// lineContinuation = "\\" lineTerminatorSequence
// ----
type LexLineContinuation[P, R any] struct {
	Term                   ohm.TerminalNode
	LineTerminatorSequence ohm.RuleNode
}

// escapeSequence
// -- rule --
// escapeSequence = unicodeEscapeSequence
// | hexEscapeSequence
// | octalEscapeSequence
// | characterEscapeSequence
// ----
type LexEscapeSequence[P, R any] struct {
	Rule ohm.RuleNode
}

// characterEscapeSequence
// -- rule --
// characterEscapeSequence = singleEscapeCharacter
// | nonEscapeCharacter
// ----
type LexCharacterEscapeSequence[P, R any] struct {
	Rule ohm.RuleNode
}

// singleEscapeCharacter
// -- rule --
// singleEscapeCharacter = "'" | "\"" | "\\" | "b" | "f" | "n" | "r" | "t" | "v"
// ----
type LexSingleEscapeCharacter[P, R any] struct {
	Term ohm.TerminalNode
}

// nonEscapeCharacter
// -- rule --
// nonEscapeCharacter = ~(escapeCharacter | lineTerminator) sourceCharacter
// ----
type LexNonEscapeCharacter[P, R any] struct {
	SourceCharacter ohm.RuleNode
}

// escapeCharacter
// -- rule --
// escapeCharacter = singleEscapeCharacter | decimalDigit | "x" | "u"
// ----
type LexEscapeCharacter[P, R any] struct {
	Arg1 ohm.Node
}

// octalEscapeSequence
// -- rule --
// octalEscapeSequence = zeroToThree octalDigit octalDigit    -- whole
// | fourToSeven octalDigit               -- eightTimesfourToSeven
// | zeroToThree octalDigit ~decimalDigit -- eightTimesZeroToThree
// | octalDigit ~decimalDigit             -- octal
//
// ----
type LexOctalEscapeSequence[P, R any] struct {
	Node ohm.Node
}

// octalEscapeSequence_whole
// -- rule --
// zeroToThree octalDigit octalDigit
// ----
type LexOctalEscapeSequenceWhole[P, R any] struct {
	ZeroToThree ohm.RuleNode
	OctalDigit1 ohm.RuleNode
	OctalDigit2 ohm.RuleNode
}

// octalEscapeSequence_eightTimesfourToSeven
// -- rule --
// fourToSeven octalDigit
// ----
type LexOctalEscapeSequenceEightTimesfourToSeven[P, R any] struct {
	FourToSeven ohm.RuleNode
	OctalDigit  ohm.RuleNode
}

// octalEscapeSequence_eightTimesZeroToThree
// -- rule --
// zeroToThree octalDigit ~decimalDigit
// ----
type LexOctalEscapeSequenceEightTimesZeroToThree[P, R any] struct {
	ZeroToThree ohm.RuleNode
	OctalDigit  ohm.RuleNode
}

// octalEscapeSequence_octal
// -- rule --
// octalDigit ~decimalDigit
// ----
type LexOctalEscapeSequenceOctal[P, R any] struct {
	OctalDigit ohm.RuleNode
}

// hexEscapeSequence
// -- rule --
// hexEscapeSequence = "x" hexDigit hexDigit
// ----
type LexHexEscapeSequence[P, R any] struct {
	Term      ohm.TerminalNode
	HexDigit1 ohm.RuleNode
	HexDigit2 ohm.RuleNode
}

// unicodeEscapeSequence
// -- rule --
// unicodeEscapeSequence = "u" hexDigit hexDigit hexDigit hexDigit
// ----
type LexUnicodeEscapeSequence[P, R any] struct {
	Term      ohm.TerminalNode
	HexDigit1 ohm.RuleNode
	HexDigit2 ohm.RuleNode
	HexDigit3 ohm.RuleNode
	HexDigit4 ohm.RuleNode
}

// zeroToThree
// -- rule --
// zeroToThree = "0".."3"
// ----
type LexZeroToThree[P, R any] struct {
	Rng ohm.TerminalNode
}

// fourToSeven
// -- rule --
// fourToSeven = "4".."7"
// ----
type LexFourToSeven[P, R any] struct {
	Rng ohm.TerminalNode
}

// regularExpressionLiteral
// -- rule --
// regularExpressionLiteral = "/" regularExpressionBody "/" regularExpressionFlags
// ----
type LexRegularExpressionLiteral[P, R any] struct {
	Term1                  ohm.TerminalNode
	RegularExpressionBody  ohm.RuleNode
	Term2                  ohm.TerminalNode
	RegularExpressionFlags ohm.RuleNode
}

// regularExpressionBody
// -- rule --
// regularExpressionBody = regularExpressionFirstChar regularExpressionChar*
// ----
type LexRegularExpressionBody[P, R any] struct {
	RegularExpressionFirstChar ohm.RuleNode
	RegularExpressionChar      ohm.ListNode
}

// regularExpressionFirstChar
// -- rule --
// regularExpressionFirstChar = ~("*" | "\\" | "/" | "[") regularExpressionNonTerminator
// | regularExpressionBackslashSequence
// | regularExpressionClass
// ----
type LexRegularExpressionFirstChar[P, R any] struct {
	Rule ohm.RuleNode
}

// regularExpressionChar
// -- rule --
// regularExpressionChar = ~("\\" | "/" | "[") regularExpressionNonTerminator
// | regularExpressionBackslashSequence
// | regularExpressionClass
// ----
type LexRegularExpressionChar[P, R any] struct {
	Rule ohm.RuleNode
}

// regularExpressionBackslashSequence
// -- rule --
// regularExpressionBackslashSequence = "\\" regularExpressionNonTerminator
// ----
type LexRegularExpressionBackslashSequence[P, R any] struct {
	Term                           ohm.TerminalNode
	RegularExpressionNonTerminator ohm.RuleNode
}

// regularExpressionNonTerminator
// -- rule --
// regularExpressionNonTerminator = ~(lineTerminator) sourceCharacter
// ----
type LexRegularExpressionNonTerminator[P, R any] struct {
	SourceCharacter ohm.RuleNode
}

// regularExpressionClass
// -- rule --
// regularExpressionClass = "[" regularExpressionClassChar* "]"
// ----
type LexRegularExpressionClass[P, R any] struct {
	Term1                      ohm.TerminalNode
	RegularExpressionClassChar ohm.ListNode
	Term2                      ohm.TerminalNode
}

// regularExpressionClassChar
// -- rule --
// regularExpressionClassChar = ~("]" | "\\") regularExpressionNonTerminator
// | regularExpressionBackslashSequence
// ----
type LexRegularExpressionClassChar[P, R any] struct {
	Rule ohm.RuleNode
}

// regularExpressionFlags
// -- rule --
// regularExpressionFlags = identifierPart*
// ----
type LexRegularExpressionFlags[P, R any] struct {
	IdentifierPart ohm.ListNode
}

// multiLineCommentNoNL
// -- rule --
// multiLineCommentNoNL = "/*" (~("*/" | lineTerminator) sourceCharacter)* "*/"
// ----
type LexMultiLineCommentNoNL[P, R any] struct {
	Term1 ohm.TerminalNode
	Alt   ohm.ListNode
	Term2 ohm.TerminalNode
}

// spacesNoNL
// -- rule --
// spacesNoNL = (whitespace | singleLineComment | multiLineCommentNoNL)*
// ----
type LexSpacesNoNL[P, R any] struct {
	Alt ohm.ListNode
}

// sc
// -- rule --
// sc = space* (";" | end)
// | spacesNoNL (lineTerminator | ~multiLineCommentNoNL multiLineComment | &"}")
// ----
type LexSc[P, R any] struct {
	Arg ohm.Node
	Alt ohm.Node
}

// break
// -- rule --
// break = "break" ~identifierPart
// ----
type LexBreak[P, R any] struct {
	Term ohm.TerminalNode
}

// do
// -- rule --
// do = "do" ~identifierPart
// ----
type LexDo[P, R any] struct {
	Term ohm.TerminalNode
}

// instanceof
// -- rule --
// instanceof = "instanceof" ~identifierPart
// ----
type LexInstanceof[P, R any] struct {
	Term ohm.TerminalNode
}

// typeof
// -- rule --
// typeof = "typeof" ~identifierPart
// ----
type LexTypeof[P, R any] struct {
	Term ohm.TerminalNode
}

// case
// -- rule --
// case = "case" ~identifierPart
// ----
type LexCase[P, R any] struct {
	Term ohm.TerminalNode
}

// else
// -- rule --
// else = "else" ~identifierPart
// ----
type LexElse[P, R any] struct {
	Term ohm.TerminalNode
}

// new
// -- rule --
// new = "new" ~identifierPart
// ----
type LexNew[P, R any] struct {
	Term ohm.TerminalNode
}

// var
// -- rule --
// var = "var" ~identifierPart
// ----
type LexVar[P, R any] struct {
	Term ohm.TerminalNode
}

// catch
// -- rule --
// catch = "catch" ~identifierPart
// ----
type LexCatch[P, R any] struct {
	Term ohm.TerminalNode
}

// finally
// -- rule --
// finally = "finally" ~identifierPart
// ----
type LexFinally[P, R any] struct {
	Term ohm.TerminalNode
}

// return
// -- rule --
// return = "return" ~identifierPart
// ----
type LexReturn[P, R any] struct {
	Term ohm.TerminalNode
}

// void
// -- rule --
// void = "void" ~identifierPart
// ----
type LexVoid[P, R any] struct {
	Term ohm.TerminalNode
}

// continue
// -- rule --
// continue = "continue" ~identifierPart
// ----
type LexContinue[P, R any] struct {
	Term ohm.TerminalNode
}

// for
// -- rule --
// for = "for" ~identifierPart
// ----
type LexFor[P, R any] struct {
	Term ohm.TerminalNode
}

// switch
// -- rule --
// switch = "switch" ~identifierPart
// ----
type LexSwitch[P, R any] struct {
	Term ohm.TerminalNode
}

// while
// -- rule --
// while = "while" ~identifierPart
// ----
type LexWhile[P, R any] struct {
	Term ohm.TerminalNode
}

// debugger
// -- rule --
// debugger = "debugger" ~identifierPart
// ----
type LexDebugger[P, R any] struct {
	Term ohm.TerminalNode
}

// function
// -- rule --
// function = "function" ~identifierPart
// ----
type LexFunction[P, R any] struct {
	Term ohm.TerminalNode
}

// this
// -- rule --
// this = "this" ~identifierPart
// ----
type LexThis[P, R any] struct {
	Term ohm.TerminalNode
}

// with
// -- rule --
// with = "with" ~identifierPart
// ----
type LexWith[P, R any] struct {
	Term ohm.TerminalNode
}

// default
// -- rule --
// default = "default" ~identifierPart
// ----
type LexDefault[P, R any] struct {
	Term ohm.TerminalNode
}

// if
// -- rule --
// if = "if" ~identifierPart
// ----
type LexIf[P, R any] struct {
	Term ohm.TerminalNode
}

// throw
// -- rule --
// throw = "throw" ~identifierPart
// ----
type LexThrow[P, R any] struct {
	Term ohm.TerminalNode
}

// delete
// -- rule --
// delete = "delete" ~identifierPart
// ----
type LexDelete[P, R any] struct {
	Term ohm.TerminalNode
}

// in
// -- rule --
// in = "in" ~identifierPart
// ----
type LexIn[P, R any] struct {
	Term ohm.TerminalNode
}

// try
// -- rule --
// try = "try" ~identifierPart
// ----
type LexTry[P, R any] struct {
	Term ohm.TerminalNode
}

// get
// -- rule --
// get = "get" ~identifierPart
// ----
type LexGet[P, R any] struct {
	Term ohm.TerminalNode
}

// set
// -- rule --
// set = "set" ~identifierPart
// ----
type LexSet[P, R any] struct {
	Term ohm.TerminalNode
}

// class
// -- rule --
// class = "class" ~identifierPart
// ----
type LexClass[P, R any] struct {
	Term ohm.TerminalNode
}

// enum
// -- rule --
// enum = "enum" ~identifierPart
// ----
type LexEnum[P, R any] struct {
	Term ohm.TerminalNode
}

// extends
// -- rule --
// extends = "extends" ~identifierPart
// ----
type LexExtends[P, R any] struct {
	Term ohm.TerminalNode
}

// super
// -- rule --
// super = "super" ~identifierPart
// ----
type LexSuper[P, R any] struct {
	Term ohm.TerminalNode
}

// const
// -- rule --
// const = "const" ~identifierPart
// ----
type LexConst[P, R any] struct {
	Term ohm.TerminalNode
}

// export
// -- rule --
// export = "export" ~identifierPart
// ----
type LexExport[P, R any] struct {
	Term ohm.TerminalNode
}

// import
// -- rule --
// import = "import" ~identifierPart
// ----
type LexImport[P, R any] struct {
	Term ohm.TerminalNode
}

// implements
// -- rule --
// implements = "implements" ~identifierPart
// ----
type LexImplements[P, R any] struct {
	Term ohm.TerminalNode
}

// let
// -- rule --
// let = "let" ~identifierPart
// ----
type LexLet[P, R any] struct {
	Term ohm.TerminalNode
}

// private
// -- rule --
// private = "private" ~identifierPart
// ----
type LexPrivate[P, R any] struct {
	Term ohm.TerminalNode
}

// public
// -- rule --
// public = "public" ~identifierPart
// ----
type LexPublic[P, R any] struct {
	Term ohm.TerminalNode
}

// interface
// -- rule --
// interface = "interface" ~identifierPart
// ----
type LexInterface[P, R any] struct {
	Term ohm.TerminalNode
}

// package
// -- rule --
// package = "package" ~identifierPart
// ----
type LexPackage[P, R any] struct {
	Term ohm.TerminalNode
}

// protected
// -- rule --
// protected = "protected" ~identifierPart
// ----
type LexProtected[P, R any] struct {
	Term ohm.TerminalNode
}

// static
// -- rule --
// static = "static" ~identifierPart
// ----
type LexStatic[P, R any] struct {
	Term ohm.TerminalNode
}

// yield
// -- rule --
// yield = "yield" ~identifierPart
// ----
type LexYield[P, R any] struct {
	Term ohm.TerminalNode
}

// noIn
// -- rule --
// noIn = ~in
// ----
type LexNoIn[P, R any] struct {
}

// withIn
// -- rule --
// withIn =
//
// // §A.3 Expressions -- https://es5.github.io/#A.3
//
// ----
type LexWithIn[P, R any] struct {
}

// PrimaryExpression
// -- rule --
// PrimaryExpression = this
// | identifier
// | literal
// // ( litToken.type === "regexp"
// //   ? this.ast(_fromIdx, "RegExpExpr",{body:  litToken.value.body
// //                            flags: litToken.value.flags}, [])
// //   : this.ast(_fromIdx, "LiteralExpr",{type:  litToken.type
// //                             value: litToken.value}, []) )
// | ArrayLiteral
// | ObjectLiteral
// | "(" Expression<withIn> ")"  -- parenExpr
//
// ----
type PrimaryExpression[P, R any] struct {
	Node ohm.Node
}

// PrimaryExpression_parenExpr
// -- rule --
// "(" Expression<withIn> ")"
// ----
type PrimaryExpressionParenExpr[P, R any] struct {
	Term1      ohm.TerminalNode
	Expression ohm.Node
	Term2      ohm.TerminalNode
}

// ArrayLiteral
// -- rule --
// ArrayLiteral = "[" ListOf<AssignmentExpressionOrElision, ","> "]"
// ----
type ArrayLiteral[P, R any] struct {
	Term1  ohm.TerminalNode
	ListOf ohm.BHorNode
	Term2  ohm.TerminalNode
}

// AssignmentExpressionOrElision
// -- rule --
// AssignmentExpressionOrElision = AssignmentExpression<withIn>
// |                       -- elision
//
// ----
type AssignmentExpressionOrElision[P, R any] struct {
	Node ohm.Node
}

// AssignmentExpressionOrElision_elision
// -- rule --
//
// ----
type AssignmentExpressionOrElisionElision[P, R any] struct {
}

// ObjectLiteral
// -- rule --
// ObjectLiteral = "{" ListOf<PropertyAssignment, ","> "}"              -- noTrailingComma
// | "{" NonemptyListOf<PropertyAssignment, ","> "," "}"  -- trailingComma
//
// ----
type ObjectLiteral[P, R any] struct {
	Node ohm.Node
}

// ObjectLiteral_noTrailingComma
// -- rule --
// "{" ListOf<PropertyAssignment, ","> "}"
// ----
type ObjectLiteralNoTrailingComma[P, R any] struct {
	Term1  ohm.TerminalNode
	ListOf ohm.BHorNode
	Term2  ohm.TerminalNode
}

// ObjectLiteral_trailingComma
// -- rule --
// "{" NonemptyListOf<PropertyAssignment, ","> "," "}"
// ----
type ObjectLiteralTrailingComma[P, R any] struct {
	Term1          ohm.TerminalNode
	NonemptyListOf ohm.BHorNode
	Term2          ohm.TerminalNode
	Term3          ohm.TerminalNode
}

// PropertyAssignment
// -- rule --
// PropertyAssignment = get PropertyName "(" ")" "{" FunctionBody "}"                  -- getter
// | set PropertyName "(" FormalParameter ")" "{" FunctionBody "}"  -- setter
// | PropertyName ":" AssignmentExpression<withIn>                  -- simple
//
// ----
type PropertyAssignment[P, R any] struct {
	Node ohm.Node
}

// PropertyAssignment_getter
// -- rule --
// get PropertyName "(" ")" "{" FunctionBody "}"
// ----
type PropertyAssignmentGetter[P, R any] struct {
	Get          ohm.RuleNode
	PropertyName ohm.RuleNode
	Term1        ohm.TerminalNode
	Term2        ohm.TerminalNode
	Term3        ohm.TerminalNode
	FunctionBody ohm.RuleNode
	Term4        ohm.TerminalNode
}

// PropertyAssignment_setter
// -- rule --
// set PropertyName "(" FormalParameter ")" "{" FunctionBody "}"
// ----
type PropertyAssignmentSetter[P, R any] struct {
	Set             ohm.RuleNode
	PropertyName    ohm.RuleNode
	Term1           ohm.TerminalNode
	FormalParameter ohm.RuleNode
	Term2           ohm.TerminalNode
	Term3           ohm.TerminalNode
	FunctionBody    ohm.RuleNode
	Term4           ohm.TerminalNode
}

// PropertyAssignment_simple
// -- rule --
// PropertyName ":" AssignmentExpression<withIn>
// ----
type PropertyAssignmentSimple[P, R any] struct {
	PropertyName         ohm.RuleNode
	Term                 ohm.TerminalNode
	AssignmentExpression ohm.Node
}

// PropertyName
// -- rule --
// PropertyName = identifierName
// | stringLiteral
// | numericLiteral
// ----
type PropertyName[P, R any] struct {
	Rule ohm.RuleNode
}

// MemberExpression
// -- rule --
// MemberExpression = MemberExpression "[" Expression<withIn> "]"  -- arrayRefExp
// | MemberExpression "." identifierName  -- propRefExp
// | new MemberExpression Arguments       -- newExp
// | FunctionExpression
// | PrimaryExpression
// ----
type MemberExpression[P, R any] struct {
	Node ohm.Node
}

// MemberExpression_arrayRefExp
// -- rule --
// MemberExpression "[" Expression<withIn> "]"
// ----
type MemberExpressionArrayRefExp[P, R any] struct {
	MemberExpression ohm.RuleNode
	Term1            ohm.TerminalNode
	Expression       ohm.Node
	Term2            ohm.TerminalNode
}

// MemberExpression_propRefExp
// -- rule --
// MemberExpression "." identifierName
// ----
type MemberExpressionPropRefExp[P, R any] struct {
	MemberExpression ohm.RuleNode
	Term             ohm.TerminalNode
	IdentifierName   ohm.RuleNode
}

// MemberExpression_newExp
// -- rule --
// new MemberExpression Arguments
// ----
type MemberExpressionNewExp[P, R any] struct {
	New              ohm.RuleNode
	MemberExpression ohm.RuleNode
	Arguments        ohm.RuleNode
}

// NewExpression
// -- rule --
// NewExpression = MemberExpression
// | new NewExpression -- newExp
//
// ----
type NewExpression[P, R any] struct {
	Node ohm.Node
}

// NewExpression_newExp
// -- rule --
// new NewExpression
// ----
type NewExpressionNewExp[P, R any] struct {
	New           ohm.RuleNode
	NewExpression ohm.RuleNode
}

// CallExpression
// -- rule --
// CallExpression = CallExpression "[" Expression<withIn> "]"  -- arrayRefExp
// | CallExpression "." identifierName  -- propRefExp
// | CallExpression Arguments           -- callExpExp
// | MemberExpression Arguments         -- memberExpExp
//
// ----
type CallExpression[P, R any] struct {
	Node ohm.Node
}

// CallExpression_arrayRefExp
// -- rule --
// CallExpression "[" Expression<withIn> "]"
// ----
type CallExpressionArrayRefExp[P, R any] struct {
	CallExpression ohm.RuleNode
	Term1          ohm.TerminalNode
	Expression     ohm.Node
	Term2          ohm.TerminalNode
}

// CallExpression_propRefExp
// -- rule --
// CallExpression "." identifierName
// ----
type CallExpressionPropRefExp[P, R any] struct {
	CallExpression ohm.RuleNode
	Term           ohm.TerminalNode
	IdentifierName ohm.RuleNode
}

// CallExpression_callExpExp
// -- rule --
// CallExpression Arguments
// ----
type CallExpressionCallExpExp[P, R any] struct {
	CallExpression ohm.RuleNode
	Arguments      ohm.RuleNode
}

// CallExpression_memberExpExp
// -- rule --
// MemberExpression Arguments
// ----
type CallExpressionMemberExpExp[P, R any] struct {
	MemberExpression ohm.RuleNode
	Arguments        ohm.RuleNode
}

// Arguments
// -- rule --
// Arguments = "(" ListOf<AssignmentExpression<withIn>, ","> ")"
// ----
type Arguments[P, R any] struct {
	Term1  ohm.TerminalNode
	ListOf ohm.BHorNode
	Term2  ohm.TerminalNode
}

// LeftHandSideExpression
// -- rule --
// LeftHandSideExpression = CallExpression
// | NewExpression
// ----
type LeftHandSideExpression[P, R any] struct {
	Rule ohm.RuleNode
}

// PostfixExpression
// -- rule --
// PostfixExpression = LeftHandSideExpression #(spacesNoNL "++")  -- postIncrement
// | LeftHandSideExpression #(spacesNoNL "--")  -- postDecrement
// | LeftHandSideExpression
// ----
type PostfixExpression[P, R any] struct {
	Node ohm.Node
}

// PostfixExpression_postIncrement
// -- rule --
// LeftHandSideExpression #(spacesNoNL "++")
// ----
type PostfixExpressionPostIncrement[P, R any] struct {
	LeftHandSideExpression ohm.RuleNode
	Alt                    ohm.Node
}

// PostfixExpression_postDecrement
// -- rule --
// LeftHandSideExpression #(spacesNoNL "--")
// ----
type PostfixExpressionPostDecrement[P, R any] struct {
	LeftHandSideExpression ohm.RuleNode
	Alt                    ohm.Node
}

// UnaryExpression
// -- rule --
// UnaryExpression = delete UnaryExpression  -- deleteExp
// | void   UnaryExpression  -- voidExp
// | typeof UnaryExpression  -- typeofExp
// | "++"   UnaryExpression  -- preIncrement
// | "--"   UnaryExpression  -- preDecrement
// | "+"    UnaryExpression  -- unaryPlus
// | "-"    UnaryExpression  -- unaryMinus
// | "~"    UnaryExpression  -- bnot
// | "!"    UnaryExpression  -- lnot
// | PostfixExpression
// ----
type UnaryExpression[P, R any] struct {
	Node ohm.Node
}

// UnaryExpression_deleteExp
// -- rule --
// delete UnaryExpression
// ----
type UnaryExpressionDeleteExp[P, R any] struct {
	Delete          ohm.RuleNode
	UnaryExpression ohm.RuleNode
}

// UnaryExpression_voidExp
// -- rule --
// void   UnaryExpression
// ----
type UnaryExpressionVoidExp[P, R any] struct {
	Void            ohm.RuleNode
	UnaryExpression ohm.RuleNode
}

// UnaryExpression_typeofExp
// -- rule --
// typeof UnaryExpression
// ----
type UnaryExpressionTypeofExp[P, R any] struct {
	Typeof          ohm.RuleNode
	UnaryExpression ohm.RuleNode
}

// UnaryExpression_preIncrement
// -- rule --
// "++"   UnaryExpression
// ----
type UnaryExpressionPreIncrement[P, R any] struct {
	Term            ohm.TerminalNode
	UnaryExpression ohm.RuleNode
}

// UnaryExpression_preDecrement
// -- rule --
// "--"   UnaryExpression
// ----
type UnaryExpressionPreDecrement[P, R any] struct {
	Term            ohm.TerminalNode
	UnaryExpression ohm.RuleNode
}

// UnaryExpression_unaryPlus
// -- rule --
// "+"    UnaryExpression
// ----
type UnaryExpressionUnaryPlus[P, R any] struct {
	Term            ohm.TerminalNode
	UnaryExpression ohm.RuleNode
}

// UnaryExpression_unaryMinus
// -- rule --
// "-"    UnaryExpression
// ----
type UnaryExpressionUnaryMinus[P, R any] struct {
	Term            ohm.TerminalNode
	UnaryExpression ohm.RuleNode
}

// UnaryExpression_bnot
// -- rule --
// "~"    UnaryExpression
// ----
type UnaryExpressionBnot[P, R any] struct {
	Term            ohm.TerminalNode
	UnaryExpression ohm.RuleNode
}

// UnaryExpression_lnot
// -- rule --
// "!"    UnaryExpression
// ----
type UnaryExpressionLnot[P, R any] struct {
	Term            ohm.TerminalNode
	UnaryExpression ohm.RuleNode
}

// MultiplicativeExpression
// -- rule --
// MultiplicativeExpression = MultiplicativeExpression "*" UnaryExpression -- mul
// | MultiplicativeExpression "/" UnaryExpression -- div
// | MultiplicativeExpression "%" UnaryExpression -- mod
// | UnaryExpression
// ----
type MultiplicativeExpression[P, R any] struct {
	Node ohm.Node
}

// MultiplicativeExpression_mul
// -- rule --
// MultiplicativeExpression "*" UnaryExpression
// ----
type MultiplicativeExpressionMul[P, R any] struct {
	MultiplicativeExpression ohm.RuleNode
	Term                     ohm.TerminalNode
	UnaryExpression          ohm.RuleNode
}

// MultiplicativeExpression_div
// -- rule --
// MultiplicativeExpression "/" UnaryExpression
// ----
type MultiplicativeExpressionDiv[P, R any] struct {
	MultiplicativeExpression ohm.RuleNode
	Term                     ohm.TerminalNode
	UnaryExpression          ohm.RuleNode
}

// MultiplicativeExpression_mod
// -- rule --
// MultiplicativeExpression "%" UnaryExpression
// ----
type MultiplicativeExpressionMod[P, R any] struct {
	MultiplicativeExpression ohm.RuleNode
	Term                     ohm.TerminalNode
	UnaryExpression          ohm.RuleNode
}

// AdditiveExpression
// -- rule --
// AdditiveExpression = AdditiveExpression "+" MultiplicativeExpression -- add
// | AdditiveExpression "-" MultiplicativeExpression -- sub
// | MultiplicativeExpression
// ----
type AdditiveExpression[P, R any] struct {
	Node ohm.Node
}

// AdditiveExpression_add
// -- rule --
// AdditiveExpression "+" MultiplicativeExpression
// ----
type AdditiveExpressionAdd[P, R any] struct {
	AdditiveExpression       ohm.RuleNode
	Term                     ohm.TerminalNode
	MultiplicativeExpression ohm.RuleNode
}

// AdditiveExpression_sub
// -- rule --
// AdditiveExpression "-" MultiplicativeExpression
// ----
type AdditiveExpressionSub[P, R any] struct {
	AdditiveExpression       ohm.RuleNode
	Term                     ohm.TerminalNode
	MultiplicativeExpression ohm.RuleNode
}

// ShiftExpression
// -- rule --
// ShiftExpression = ShiftExpression "<<" AdditiveExpression  -- lsl
// | ShiftExpression ">>>" AdditiveExpression -- lsr
// | ShiftExpression ">>" AdditiveExpression  -- asr
// | AdditiveExpression
// ----
type ShiftExpression[P, R any] struct {
	Node ohm.Node
}

// ShiftExpression_lsl
// -- rule --
// ShiftExpression "<<" AdditiveExpression
// ----
type ShiftExpressionLsl[P, R any] struct {
	ShiftExpression    ohm.RuleNode
	Term               ohm.TerminalNode
	AdditiveExpression ohm.RuleNode
}

// ShiftExpression_lsr
// -- rule --
// ShiftExpression ">>>" AdditiveExpression
// ----
type ShiftExpressionLsr[P, R any] struct {
	ShiftExpression    ohm.RuleNode
	Term               ohm.TerminalNode
	AdditiveExpression ohm.RuleNode
}

// ShiftExpression_asr
// -- rule --
// ShiftExpression ">>" AdditiveExpression
// ----
type ShiftExpressionAsr[P, R any] struct {
	ShiftExpression    ohm.RuleNode
	Term               ohm.TerminalNode
	AdditiveExpression ohm.RuleNode
}

// RelationalExpression
// -- rule --
// RelationalExpression<guardIn>
// = RelationalExpression<guardIn> "<" ShiftExpression           -- lt
// | RelationalExpression<guardIn> ">" ShiftExpression           -- gt
// | RelationalExpression<guardIn> "<=" ShiftExpression          -- le
// | RelationalExpression<guardIn> ">=" ShiftExpression          -- ge
// | RelationalExpression<guardIn> "instanceof" ShiftExpression  -- instanceOfExp
// | RelationalExpression<guardIn> guardIn "in" ShiftExpression  -- inExp
// | ShiftExpression
// ----
type RelationalExpression[P, R any] struct {
	Node ohm.Node
}

// RelationalExpression_lt
// -- rule --
// RelationalExpression<guardIn> "<" ShiftExpression
// ----
type RelationalExpressionLt[P, R any] struct {
	RelationalExpression ohm.Node
	Term                 ohm.TerminalNode
	ShiftExpression      ohm.RuleNode
}

// RelationalExpression_gt
// -- rule --
// RelationalExpression<guardIn> ">" ShiftExpression
// ----
type RelationalExpressionGt[P, R any] struct {
	RelationalExpression ohm.Node
	Term                 ohm.TerminalNode
	ShiftExpression      ohm.RuleNode
}

// RelationalExpression_le
// -- rule --
// RelationalExpression<guardIn> "<=" ShiftExpression
// ----
type RelationalExpressionLe[P, R any] struct {
	RelationalExpression ohm.Node
	Term                 ohm.TerminalNode
	ShiftExpression      ohm.RuleNode
}

// RelationalExpression_ge
// -- rule --
// RelationalExpression<guardIn> ">=" ShiftExpression
// ----
type RelationalExpressionGe[P, R any] struct {
	RelationalExpression ohm.Node
	Term                 ohm.TerminalNode
	ShiftExpression      ohm.RuleNode
}

// RelationalExpression_instanceOfExp
// -- rule --
// RelationalExpression<guardIn> "instanceof" ShiftExpression
// ----
type RelationalExpressionInstanceOfExp[P, R any] struct {
	RelationalExpression ohm.Node
	Term                 ohm.TerminalNode
	ShiftExpression      ohm.RuleNode
}

// RelationalExpression_inExp
// -- rule --
// RelationalExpression<guardIn> guardIn "in" ShiftExpression
// ----
type RelationalExpressionInExp[P, R any] struct {
	RelationalExpression ohm.Node
	GuardIn              ohm.RuleNode
	Term                 ohm.TerminalNode
	ShiftExpression      ohm.RuleNode
}

// EqualityExpression
// -- rule --
// EqualityExpression<guardIn>
// = EqualityExpression<guardIn> "==" RelationalExpression<guardIn>  -- equal
// | EqualityExpression<guardIn> "!=" RelationalExpression<guardIn>  -- notEqual
// | EqualityExpression<guardIn> "===" RelationalExpression<guardIn> -- eq
// | EqualityExpression<guardIn> "!==" RelationalExpression<guardIn> -- notEq
// | RelationalExpression<guardIn>
// ----
type EqualityExpression[P, R any] struct {
	Node ohm.Node
}

// EqualityExpression_equal
// -- rule --
// EqualityExpression<guardIn> "==" RelationalExpression<guardIn>
// ----
type EqualityExpressionEqual[P, R any] struct {
	EqualityExpression   ohm.Node
	Term                 ohm.TerminalNode
	RelationalExpression ohm.Node
}

// EqualityExpression_notEqual
// -- rule --
// EqualityExpression<guardIn> "!=" RelationalExpression<guardIn>
// ----
type EqualityExpressionNotEqual[P, R any] struct {
	EqualityExpression   ohm.Node
	Term                 ohm.TerminalNode
	RelationalExpression ohm.Node
}

// EqualityExpression_eq
// -- rule --
// EqualityExpression<guardIn> "===" RelationalExpression<guardIn>
// ----
type EqualityExpressionEq[P, R any] struct {
	EqualityExpression   ohm.Node
	Term                 ohm.TerminalNode
	RelationalExpression ohm.Node
}

// EqualityExpression_notEq
// -- rule --
// EqualityExpression<guardIn> "!==" RelationalExpression<guardIn>
// ----
type EqualityExpressionNotEq[P, R any] struct {
	EqualityExpression   ohm.Node
	Term                 ohm.TerminalNode
	RelationalExpression ohm.Node
}

// BitwiseANDExpression
// -- rule --
// BitwiseANDExpression<guardIn>
// = BitwiseANDExpression<guardIn> "&" EqualityExpression<guardIn> -- band
// | EqualityExpression<guardIn>
// ----
type BitwiseANDExpression[P, R any] struct {
	Node ohm.Node
}

// BitwiseANDExpression_band
// -- rule --
// BitwiseANDExpression<guardIn> "&" EqualityExpression<guardIn>
// ----
type BitwiseANDExpressionBand[P, R any] struct {
	BitwiseANDExpression ohm.Node
	Term                 ohm.TerminalNode
	EqualityExpression   ohm.Node
}

// BitwiseXORExpression
// -- rule --
// BitwiseXORExpression<guardIn>
// = BitwiseXORExpression<guardIn> "^" BitwiseANDExpression<guardIn> -- bxor
// | BitwiseANDExpression<guardIn>
// ----
type BitwiseXORExpression[P, R any] struct {
	Node ohm.Node
}

// BitwiseXORExpression_bxor
// -- rule --
// BitwiseXORExpression<guardIn> "^" BitwiseANDExpression<guardIn>
// ----
type BitwiseXORExpressionBxor[P, R any] struct {
	BitwiseXORExpression ohm.Node
	Term                 ohm.TerminalNode
	BitwiseANDExpression ohm.Node
}

// BitwiseORExpression
// -- rule --
// BitwiseORExpression<guardIn>
// = BitwiseORExpression<guardIn> "|" BitwiseXORExpression<guardIn> -- bor
// | BitwiseXORExpression<guardIn>
// ----
type BitwiseORExpression[P, R any] struct {
	Node ohm.Node
}

// BitwiseORExpression_bor
// -- rule --
// BitwiseORExpression<guardIn> "|" BitwiseXORExpression<guardIn>
// ----
type BitwiseORExpressionBor[P, R any] struct {
	BitwiseORExpression  ohm.Node
	Term                 ohm.TerminalNode
	BitwiseXORExpression ohm.Node
}

// LogicalANDExpression
// -- rule --
// LogicalANDExpression<guardIn>
// = LogicalANDExpression<guardIn> "&&" BitwiseORExpression<guardIn> -- land
// | BitwiseORExpression<guardIn>
// ----
type LogicalANDExpression[P, R any] struct {
	Node ohm.Node
}

// LogicalANDExpression_land
// -- rule --
// LogicalANDExpression<guardIn> "&&" BitwiseORExpression<guardIn>
// ----
type LogicalANDExpressionLand[P, R any] struct {
	LogicalANDExpression ohm.Node
	Term                 ohm.TerminalNode
	BitwiseORExpression  ohm.Node
}

// LogicalORExpression
// -- rule --
// LogicalORExpression<guardIn>
// = LogicalORExpression<guardIn> "||" LogicalANDExpression<guardIn> -- lor
// | LogicalANDExpression<guardIn>
// ----
type LogicalORExpression[P, R any] struct {
	Node ohm.Node
}

// LogicalORExpression_lor
// -- rule --
// LogicalORExpression<guardIn> "||" LogicalANDExpression<guardIn>
// ----
type LogicalORExpressionLor[P, R any] struct {
	LogicalORExpression  ohm.Node
	Term                 ohm.TerminalNode
	LogicalANDExpression ohm.Node
}

// ConditionalExpression
// -- rule --
// ConditionalExpression<guardIn>
// = LogicalORExpression<guardIn> "?" AssignmentExpression<withIn> ":" AssignmentExpression<guardIn> -- conditional
// | LogicalORExpression<guardIn>
// ----
type ConditionalExpression[P, R any] struct {
	Node ohm.Node
}

// ConditionalExpression_conditional
// -- rule --
// LogicalORExpression<guardIn> "?" AssignmentExpression<withIn> ":" AssignmentExpression<guardIn>
// ----
type ConditionalExpressionConditional[P, R any] struct {
	LogicalORExpression   ohm.Node
	Term1                 ohm.TerminalNode
	AssignmentExpression1 ohm.Node
	Term2                 ohm.TerminalNode
	AssignmentExpression2 ohm.Node
}

// AssignmentExpression
// -- rule --
// AssignmentExpression<guardIn>
// = LeftHandSideExpression assignmentOperator AssignmentExpression<guardIn> -- assignment
// | ConditionalExpression<guardIn>
// ----
type AssignmentExpression[P, R any] struct {
	Node ohm.Node
}

// AssignmentExpression_assignment
// -- rule --
// LeftHandSideExpression assignmentOperator AssignmentExpression<guardIn>
// ----
type AssignmentExpressionAssignment[P, R any] struct {
	LeftHandSideExpression ohm.RuleNode
	AssignmentOperator     ohm.RuleNode
	AssignmentExpression   ohm.Node
}

// Expression - an expression
// -- rule --
// Expression<guardIn> (an expression)
// = Expression<guardIn> "," AssignmentExpression<guardIn> -- commaExp
// | AssignmentExpression<guardIn>
// ----
type Expression[P, R any] struct {
	Node ohm.Node
}

// Expression_commaExp
// -- rule --
// Expression<guardIn> "," AssignmentExpression<guardIn>
// ----
type ExpressionCommaExp[P, R any] struct {
	Expression           ohm.Node
	Term                 ohm.TerminalNode
	AssignmentExpression ohm.Node
}

// assignmentOperator
// -- rule --
// assignmentOperator = "=" | ">>>=" | "<<=" | ">>="
// | "*=" | "/=" | "%=" | "+=" | "-=" | "&=" | "^=" | "|="
// ----
type LexAssignmentOperator[P, R any] struct {
	Term ohm.TerminalNode
}

// Statement
// -- rule --
// Statement
// = Block
// | VariableStatement
// | EmptyStatement
// | ExpressionStatement
// | IfStatement
// | IterationStatement
// | ContinueStatement
// | BreakStatement
// | ReturnStatement
// | WithStatement
// | LabelledStatement
// | SwitchStatement
// | ThrowStatement
// | TryStatement
// | DebuggerStatement
// ----
type Statement[P, R any] struct {
	Rule ohm.RuleNode
}

// Block
// -- rule --
// Block = "{" StatementList "}"
// ----
type Block[P, R any] struct {
	Term1         ohm.TerminalNode
	StatementList ohm.RuleNode
	Term2         ohm.TerminalNode
}

// StatementList
// -- rule --
// StatementList = Statement*
// ----
type StatementList[P, R any] struct {
	Statement ohm.ListNode
}

// VariableStatement
// -- rule --
// VariableStatement = var VariableDeclarationList<withIn> #sc
// ----
type VariableStatement[P, R any] struct {
	Var                     ohm.RuleNode
	VariableDeclarationList ohm.Node
	Sc                      ohm.RuleNode
}

// VariableDeclarationList
// -- rule --
// VariableDeclarationList<guardIn> = NonemptyListOf<VariableDeclaration<guardIn>, ",">
// ----
type VariableDeclarationList[P, R any] struct {
	NonemptyListOf ohm.BHorNode
}

// VariableDeclaration
// -- rule --
// VariableDeclaration<guardIn> = identifier Initialiser<guardIn>?
// ----
type VariableDeclaration[P, R any] struct {
	Identifier  ohm.RuleNode
	Initialiser ohm.OptNode
}

// Initialiser
// -- rule --
// Initialiser<guardIn> = "=" AssignmentExpression<guardIn>
// ----
type Initialiser[P, R any] struct {
	Term                 ohm.TerminalNode
	AssignmentExpression ohm.Node
}

// EmptyStatement
// -- rule --
// EmptyStatement = ";"
// ----
type EmptyStatement[P, R any] struct {
	Term ohm.TerminalNode
}

// ExpressionStatement
// -- rule --
// ExpressionStatement = ~("{" | function) Expression<withIn> #sc
// ----
type ExpressionStatement[P, R any] struct {
	Expression ohm.Node
	Sc         ohm.RuleNode
}

// IfStatement
// -- rule --
// IfStatement = if "(" Expression<withIn> ")" Statement (else Statement)?
// ----
type IfStatement[P, R any] struct {
	If         ohm.RuleNode
	Term1      ohm.TerminalNode
	Expression ohm.Node
	Term2      ohm.TerminalNode
	Statement  ohm.RuleNode
	Alt        ohm.OptNode
}

// IterationStatement
// -- rule --
// IterationStatement = do Statement while "(" Expression<withIn> ")" #sc  -- doWhile
// | while "(" Expression<withIn> ")" Statement           -- whileDo
// | for "(" Expression<noIn>? ";"
// Expression<withIn>? ";"
// Expression<withIn>? ")" Statement          -- for3
// | for "(" var VariableDeclarationList<noIn> ";"
// Expression<withIn>? ";"
// Expression<withIn>? ")" Statement          -- for3var
// | for "(" LeftHandSideExpression in
// Expression<withIn> ")" Statement           -- forIn
// | for "(" var VariableDeclaration<noIn> in
// Expression<withIn> ")" Statement           -- forInVar
//
// ----
type IterationStatement[P, R any] struct {
	Node ohm.Node
}

// IterationStatement_doWhile
// -- rule --
// do Statement while "(" Expression<withIn> ")" #sc
// ----
type IterationStatementDoWhile[P, R any] struct {
	Do         ohm.RuleNode
	Statement  ohm.RuleNode
	While      ohm.RuleNode
	Term1      ohm.TerminalNode
	Expression ohm.Node
	Term2      ohm.TerminalNode
	Sc         ohm.RuleNode
}

// IterationStatement_whileDo
// -- rule --
// while "(" Expression<withIn> ")" Statement
// ----
type IterationStatementWhileDo[P, R any] struct {
	While      ohm.RuleNode
	Term1      ohm.TerminalNode
	Expression ohm.Node
	Term2      ohm.TerminalNode
	Statement  ohm.RuleNode
}

// IterationStatement_for3
// -- rule --
// for "(" Expression<noIn>? ";"
// Expression<withIn>? ";"
// Expression<withIn>? ")" Statement
// ----
type IterationStatementFor3[P, R any] struct {
	For         ohm.RuleNode
	Term1       ohm.TerminalNode
	Expression1 ohm.OptNode
	Term2       ohm.TerminalNode
	Expression2 ohm.OptNode
	Term3       ohm.TerminalNode
	Expression3 ohm.OptNode
	Term4       ohm.TerminalNode
	Statement   ohm.RuleNode
}

// IterationStatement_for3var
// -- rule --
// for "(" var VariableDeclarationList<noIn> ";"
// Expression<withIn>? ";"
// Expression<withIn>? ")" Statement
// ----
type IterationStatementFor3var[P, R any] struct {
	For                     ohm.RuleNode
	Term1                   ohm.TerminalNode
	Var                     ohm.RuleNode
	VariableDeclarationList ohm.Node
	Term2                   ohm.TerminalNode
	Expression1             ohm.OptNode
	Term3                   ohm.TerminalNode
	Expression2             ohm.OptNode
	Term4                   ohm.TerminalNode
	Statement               ohm.RuleNode
}

// IterationStatement_forIn
// -- rule --
// for "(" LeftHandSideExpression in
// Expression<withIn> ")" Statement
// ----
type IterationStatementForIn[P, R any] struct {
	For                    ohm.RuleNode
	Term1                  ohm.TerminalNode
	LeftHandSideExpression ohm.RuleNode
	In                     ohm.RuleNode
	Expression             ohm.Node
	Term2                  ohm.TerminalNode
	Statement              ohm.RuleNode
}

// IterationStatement_forInVar
// -- rule --
// for "(" var VariableDeclaration<noIn> in
// Expression<withIn> ")" Statement
// ----
type IterationStatementForInVar[P, R any] struct {
	For                 ohm.RuleNode
	Term1               ohm.TerminalNode
	Var                 ohm.RuleNode
	VariableDeclaration ohm.Node
	In                  ohm.RuleNode
	Expression          ohm.Node
	Term2               ohm.TerminalNode
	Statement           ohm.RuleNode
}

// ContinueStatement
// -- rule --
// ContinueStatement = continue #((spacesNoNL identifier)? sc)
// ----
type ContinueStatement[P, R any] struct {
	Continue ohm.RuleNode
	Alt      ohm.Node
}

// BreakStatement
// -- rule --
// BreakStatement = break #((spacesNoNL identifier)? sc)
// ----
type BreakStatement[P, R any] struct {
	Break ohm.RuleNode
	Alt   ohm.Node
}

// ReturnStatement
// -- rule --
// ReturnStatement = return (#(spacesNoNL ~space) Expression<withIn>)? #sc
// ----
type ReturnStatement[P, R any] struct {
	Return ohm.RuleNode
	Alt    ohm.OptNode
	Sc     ohm.RuleNode
}

// WithStatement
// -- rule --
// WithStatement = with "(" Expression<withIn> ")" Statement
// ----
type WithStatement[P, R any] struct {
	With       ohm.RuleNode
	Term1      ohm.TerminalNode
	Expression ohm.Node
	Term2      ohm.TerminalNode
	Statement  ohm.RuleNode
}

// SwitchStatement
// -- rule --
// SwitchStatement = switch "(" Expression<withIn> ")" CaseBlock
// ----
type SwitchStatement[P, R any] struct {
	Switch     ohm.RuleNode
	Term1      ohm.TerminalNode
	Expression ohm.Node
	Term2      ohm.TerminalNode
	CaseBlock  ohm.RuleNode
}

// CaseBlock
// -- rule --
// CaseBlock = "{" CaseClause* DefaultClause CaseClause* "}"  -- withDefault
// | "{"                           CaseClause* "}"  -- withoutDefault
//
// ----
type CaseBlock[P, R any] struct {
	Node ohm.Node
}

// CaseBlock_withDefault
// -- rule --
// "{" CaseClause* DefaultClause CaseClause* "}"
// ----
type CaseBlockWithDefault[P, R any] struct {
	Term1         ohm.TerminalNode
	CaseClause1   ohm.ListNode
	DefaultClause ohm.RuleNode
	CaseClause2   ohm.ListNode
	Term2         ohm.TerminalNode
}

// CaseBlock_withoutDefault
// -- rule --
// "{"                           CaseClause* "}"
// ----
type CaseBlockWithoutDefault[P, R any] struct {
	Term1      ohm.TerminalNode
	CaseClause ohm.ListNode
	Term2      ohm.TerminalNode
}

// CaseClause
// -- rule --
// CaseClause = case Expression<withIn> ":" Statement*
// ----
type CaseClause[P, R any] struct {
	Case       ohm.RuleNode
	Expression ohm.Node
	Term       ohm.TerminalNode
	Statement  ohm.ListNode
}

// DefaultClause
// -- rule --
// DefaultClause = default ":" Statement*
// ----
type DefaultClause[P, R any] struct {
	Default   ohm.RuleNode
	Term      ohm.TerminalNode
	Statement ohm.ListNode
}

// LabelledStatement
// -- rule --
// LabelledStatement = identifier ":" Statement
// ----
type LabelledStatement[P, R any] struct {
	Identifier ohm.RuleNode
	Term       ohm.TerminalNode
	Statement  ohm.RuleNode
}

// ThrowStatement
// -- rule --
// ThrowStatement = throw Expression<withIn> #sc  -- throwExpr
//
// ----
type ThrowStatement[P, R any] struct {
	Node ohm.Node
}

// ThrowStatement_throwExpr
// -- rule --
// throw Expression<withIn> #sc
// ----
type ThrowStatementThrowExpr[P, R any] struct {
	Throw      ohm.RuleNode
	Expression ohm.Node
	Sc         ohm.RuleNode
}

// TryStatement
// -- rule --
// TryStatement = try Block Catch Finally  -- tryCatchFinally
// | try Block Finally        -- tryFinally
// | try Block Catch          -- tryCatch
//
// ----
type TryStatement[P, R any] struct {
	Node ohm.Node
}

// TryStatement_tryCatchFinally
// -- rule --
// try Block Catch Finally
// ----
type TryStatementTryCatchFinally[P, R any] struct {
	Try     ohm.RuleNode
	Block   ohm.RuleNode
	Catch   ohm.RuleNode
	Finally ohm.RuleNode
}

// TryStatement_tryFinally
// -- rule --
// try Block Finally
// ----
type TryStatementTryFinally[P, R any] struct {
	Try     ohm.RuleNode
	Block   ohm.RuleNode
	Finally ohm.RuleNode
}

// TryStatement_tryCatch
// -- rule --
// try Block Catch
// ----
type TryStatementTryCatch[P, R any] struct {
	Try   ohm.RuleNode
	Block ohm.RuleNode
	Catch ohm.RuleNode
}

// Catch
// -- rule --
// Catch = catch "(" FormalParameter ")" Block
// ----
type Catch[P, R any] struct {
	Catch           ohm.RuleNode
	Term1           ohm.TerminalNode
	FormalParameter ohm.RuleNode
	Term2           ohm.TerminalNode
	Block           ohm.RuleNode
}

// Finally
// -- rule --
// Finally = finally Block
// ----
type Finally[P, R any] struct {
	Finally ohm.RuleNode
	Block   ohm.RuleNode
}

// DebuggerStatement
// -- rule --
// DebuggerStatement = #(debugger sc)
// ----
type DebuggerStatement[P, R any] struct {
	Alt ohm.Node
}

// FunctionDeclaration
// -- rule --
// FunctionDeclaration
// = function identifier "(" FormalParameterList ")" "{" FunctionBody "}"
// ----
type FunctionDeclaration[P, R any] struct {
	Function            ohm.RuleNode
	Identifier          ohm.RuleNode
	Term1               ohm.TerminalNode
	FormalParameterList ohm.RuleNode
	Term2               ohm.TerminalNode
	Term3               ohm.TerminalNode
	FunctionBody        ohm.RuleNode
	Term4               ohm.TerminalNode
}

// FunctionExpression
// -- rule --
// FunctionExpression
// = function identifier "(" FormalParameterList ")" "{" FunctionBody "}"  -- named
// | function "(" FormalParameterList ")" "{" FunctionBody "}"             -- anonymous
//
// ----
type FunctionExpression[P, R any] struct {
	Node ohm.Node
}

// FunctionExpression_named
// -- rule --
// function identifier "(" FormalParameterList ")" "{" FunctionBody "}"
// ----
type FunctionExpressionNamed[P, R any] struct {
	Function            ohm.RuleNode
	Identifier          ohm.RuleNode
	Term1               ohm.TerminalNode
	FormalParameterList ohm.RuleNode
	Term2               ohm.TerminalNode
	Term3               ohm.TerminalNode
	FunctionBody        ohm.RuleNode
	Term4               ohm.TerminalNode
}

// FunctionExpression_anonymous
// -- rule --
// function "(" FormalParameterList ")" "{" FunctionBody "}"
// ----
type FunctionExpressionAnonymous[P, R any] struct {
	Function            ohm.RuleNode
	Term1               ohm.TerminalNode
	FormalParameterList ohm.RuleNode
	Term2               ohm.TerminalNode
	Term3               ohm.TerminalNode
	FunctionBody        ohm.RuleNode
	Term4               ohm.TerminalNode
}

// FormalParameterList
// -- rule --
// FormalParameterList = ListOf<FormalParameter, ",">
// ----
type FormalParameterList[P, R any] struct {
	ListOf ohm.BHorNode
}

// FormalParameter
// -- rule --
// FormalParameter = identifier
// ----
type FormalParameter[P, R any] struct {
	Identifier ohm.RuleNode
}

// FunctionBody
// -- rule --
// FunctionBody = &(Directive*) SourceElement*
// ----
type FunctionBody[P, R any] struct {
	SourceElement ohm.ListNode
}

// SourceElement
// -- rule --
// SourceElement = Declaration | Statement
// ----
type SourceElement[P, R any] struct {
	Rule ohm.RuleNode
}

// Declaration
// -- rule --
// Declaration = FunctionDeclaration
// ----
type Declaration[P, R any] struct {
	FunctionDeclaration ohm.RuleNode
}

// Directive
// -- rule --
// Directive = stringLiteral #sc
// ----
type Directive[P, R any] struct {
	StringLiteral ohm.RuleNode
	Sc            ohm.RuleNode
}
