// Code generated by ohm-cli generate accepts - DO NOT EDIT.
/* ohm-cli generate go \
--go-type-package arith_visitor \
--generic-methods \
--output-dir arith_visitor
*/
package arith_visitor

import (
	"github.com/ohmjs/ohm-go/ohm"
)

var GrammarMetada map[string]string = map[string]string{
	"sha256": "",
}

// accepts for grammar Arithmetic
// TODO for grammar Arithmetic, implement Make func for starting rule Exp
func MakeNodeFromRoot[P, R any](root ohm.Node) ohm.AcceptorFunc[P, R] {
	kids := root.Children()
	return (&Exp{
		AddExp: kids[0].(ohm.RuleNode),
	}).Accept
}

// Accept implementation for Exp
//
// Exp
// = AddExp
func (node *Exp) Accept[P, R any](this ohm.Node, visitor any, payload P) (result R, err error) {
	ohm.AssertName(this, "Exp")
	if v, ok := visitor.(Visitor_Exp[P, R]); ok {
		v.VisitExp(node)
		return
	}
	if v, ok := visitor.(VisitorE_Exp[P, R]); ok {
		err = v.VisitExp(node)
		return
	}
	if v, ok := visitor.(VisitorP_Exp[P, R]); ok {
		v.VisitExp(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPE_Exp[P, R]); ok {
		err = v.VisitExp(node, payload)
		return
	}
	if v, ok := visitor.(VisitorR_Exp[P, R]); ok {
		result = v.VisitExp(node)
		return
	}
	if v, ok := visitor.(VisitorRE_Exp[P, R]); ok {
		result, err = v.VisitExp(node)
		return
	}
	if v, ok := visitor.(VisitorPR_Exp[P, R]); ok {
		result = v.VisitExp(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPRE_Exp[P, R]); ok {
		result, err = v.VisitExp(node, payload)
		return
	}
	ohm.TypeCheckMethod[P, R](visitor, "Exp")
	return node.DefaultAccept[P, R](visitor, payload)
}

func (node *Exp) DefaultAccept[P, R any](visitor any, payload P) (result R, err error) {
	result, err = node.AcceptAddExp[P, R](visitor, payload)
	return
}

func (node *Exp) AcceptAddExp[P, R any](visitor any, payload P) (result R, err error) {
	// Rule
	kids := node.AddExp.Children()
	result, err = (&AddExp{
		Node: kids[0],
	}).Accept[P, R](node.AddExp, visitor, payload)
	return
}

// Accept implementation for AddExp
//
// AddExp
// = AddExp "+" MulExp  -- plus
// | AddExp "-" MulExp  -- minus
// | MulExp
func (node *AddExp) Accept[P, R any](this ohm.Node, visitor any, payload P) (result R, err error) {
	ohm.AssertName(this, "AddExp")
	if v, ok := visitor.(Visitor_AddExp[P, R]); ok {
		v.VisitAddExp(node)
		return
	}
	if v, ok := visitor.(VisitorE_AddExp[P, R]); ok {
		err = v.VisitAddExp(node)
		return
	}
	if v, ok := visitor.(VisitorP_AddExp[P, R]); ok {
		v.VisitAddExp(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPE_AddExp[P, R]); ok {
		err = v.VisitAddExp(node, payload)
		return
	}
	if v, ok := visitor.(VisitorR_AddExp[P, R]); ok {
		result = v.VisitAddExp(node)
		return
	}
	if v, ok := visitor.(VisitorRE_AddExp[P, R]); ok {
		result, err = v.VisitAddExp(node)
		return
	}
	if v, ok := visitor.(VisitorPR_AddExp[P, R]); ok {
		result = v.VisitAddExp(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPRE_AddExp[P, R]); ok {
		result, err = v.VisitAddExp(node, payload)
		return
	}
	ohm.TypeCheckMethod[P, R](visitor, "AddExp")
	return node.DefaultAccept[P, R](visitor, payload)
}

func (node *AddExp) DefaultAccept[P, R any](visitor any, payload P) (result R, err error) {
	switch node.Node.CtorName() {
	case "AddExp":
		return (&AddExp{
			Node: node.Node.Children()[0].(ohm.RuleNode),
		}).DefaultAccept[P, R](visitor, payload)
	case "AddExp_plus":
		kids := node.Node.Children()
		_ = kids // only needed in rule.Branch.V is empty
		return (&AddExpPlus{
			AddExp: kids[0].(ohm.RuleNode),
			Term:   kids[1].(ohm.TerminalNode),
			MulExp: kids[2].(ohm.RuleNode),
		}).Accept[P, R](node.Node, visitor, payload)
	case "AddExp_minus":
		kids := node.Node.Children()
		_ = kids // only needed in rule.Branch.V is empty
		return (&AddExpMinus{
			AddExp: kids[0].(ohm.RuleNode),
			Term:   kids[1].(ohm.TerminalNode),
			MulExp: kids[2].(ohm.RuleNode),
		}).Accept[P, R](node.Node, visitor, payload)
	default: // bare case after named ones
		kids := node.Node.Children()
		return (&MulExp{
			Node: kids[0],
		}).Accept[P, R](node.Node, visitor, payload)
	} // end switch
}

// Accept implementation for AddExp_plus
//
// AddExp "+" MulExp
func (node *AddExpPlus) Accept[P, R any](this ohm.Node, visitor any, payload P) (result R, err error) {
	ohm.AssertName(this, "AddExp_plus")
	if v, ok := visitor.(Visitor_AddExpPlus[P, R]); ok {
		v.VisitAddExpPlus(node)
		return
	}
	if v, ok := visitor.(VisitorE_AddExpPlus[P, R]); ok {
		err = v.VisitAddExpPlus(node)
		return
	}
	if v, ok := visitor.(VisitorP_AddExpPlus[P, R]); ok {
		v.VisitAddExpPlus(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPE_AddExpPlus[P, R]); ok {
		err = v.VisitAddExpPlus(node, payload)
		return
	}
	if v, ok := visitor.(VisitorR_AddExpPlus[P, R]); ok {
		result = v.VisitAddExpPlus(node)
		return
	}
	if v, ok := visitor.(VisitorRE_AddExpPlus[P, R]); ok {
		result, err = v.VisitAddExpPlus(node)
		return
	}
	if v, ok := visitor.(VisitorPR_AddExpPlus[P, R]); ok {
		result = v.VisitAddExpPlus(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPRE_AddExpPlus[P, R]); ok {
		result, err = v.VisitAddExpPlus(node, payload)
		return
	}
	ohm.TypeCheckMethod[P, R](visitor, "AddExpPlus")
	return node.DefaultAccept[P, R](visitor, payload)
}

func (node *AddExpPlus) DefaultAccept[P, R any](visitor any, payload P) (result R, err error) {
	result, err = node.AcceptAddExp[P, R](visitor, payload)
	result, err = node.AcceptTerm[P, R](visitor, payload)
	result, err = node.AcceptMulExp[P, R](visitor, payload)
	return
}

func (node *AddExpPlus) AcceptAddExp[P, R any](visitor any, payload P) (result R, err error) {
	// Rule
	kids := node.AddExp.Children()
	result, err = (&AddExp{
		Node: kids[0],
	}).Accept[P, R](node.AddExp, visitor, payload)
	return
}

func (node *AddExpPlus) AcceptTerm[P, R any](visitor any, payload P) (result R, err error) {
	// Term
	if v, ok := visitor.(ohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *AddExpPlus) AcceptMulExp[P, R any](visitor any, payload P) (result R, err error) {
	// Rule
	kids := node.MulExp.Children()
	result, err = (&MulExp{
		Node: kids[0],
	}).Accept[P, R](node.MulExp, visitor, payload)
	return
}

// Accept implementation for AddExp_minus
//
// AddExp "-" MulExp
func (node *AddExpMinus) Accept[P, R any](this ohm.Node, visitor any, payload P) (result R, err error) {
	ohm.AssertName(this, "AddExp_minus")
	if v, ok := visitor.(Visitor_AddExpMinus[P, R]); ok {
		v.VisitAddExpMinus(node)
		return
	}
	if v, ok := visitor.(VisitorE_AddExpMinus[P, R]); ok {
		err = v.VisitAddExpMinus(node)
		return
	}
	if v, ok := visitor.(VisitorP_AddExpMinus[P, R]); ok {
		v.VisitAddExpMinus(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPE_AddExpMinus[P, R]); ok {
		err = v.VisitAddExpMinus(node, payload)
		return
	}
	if v, ok := visitor.(VisitorR_AddExpMinus[P, R]); ok {
		result = v.VisitAddExpMinus(node)
		return
	}
	if v, ok := visitor.(VisitorRE_AddExpMinus[P, R]); ok {
		result, err = v.VisitAddExpMinus(node)
		return
	}
	if v, ok := visitor.(VisitorPR_AddExpMinus[P, R]); ok {
		result = v.VisitAddExpMinus(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPRE_AddExpMinus[P, R]); ok {
		result, err = v.VisitAddExpMinus(node, payload)
		return
	}
	ohm.TypeCheckMethod[P, R](visitor, "AddExpMinus")
	return node.DefaultAccept[P, R](visitor, payload)
}

func (node *AddExpMinus) DefaultAccept[P, R any](visitor any, payload P) (result R, err error) {
	result, err = node.AcceptAddExp[P, R](visitor, payload)
	result, err = node.AcceptTerm[P, R](visitor, payload)
	result, err = node.AcceptMulExp[P, R](visitor, payload)
	return
}

func (node *AddExpMinus) AcceptAddExp[P, R any](visitor any, payload P) (result R, err error) {
	// Rule
	kids := node.AddExp.Children()
	result, err = (&AddExp{
		Node: kids[0],
	}).Accept[P, R](node.AddExp, visitor, payload)
	return
}

func (node *AddExpMinus) AcceptTerm[P, R any](visitor any, payload P) (result R, err error) {
	// Term
	if v, ok := visitor.(ohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *AddExpMinus) AcceptMulExp[P, R any](visitor any, payload P) (result R, err error) {
	// Rule
	kids := node.MulExp.Children()
	result, err = (&MulExp{
		Node: kids[0],
	}).Accept[P, R](node.MulExp, visitor, payload)
	return
}

// Accept implementation for MulExp
//
// MulExp
// = MulExp "*" PriExp  -- times
// | MulExp "/" PriExp  -- divide
// | PriExp
func (node *MulExp) Accept[P, R any](this ohm.Node, visitor any, payload P) (result R, err error) {
	ohm.AssertName(this, "MulExp")
	if v, ok := visitor.(Visitor_MulExp[P, R]); ok {
		v.VisitMulExp(node)
		return
	}
	if v, ok := visitor.(VisitorE_MulExp[P, R]); ok {
		err = v.VisitMulExp(node)
		return
	}
	if v, ok := visitor.(VisitorP_MulExp[P, R]); ok {
		v.VisitMulExp(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPE_MulExp[P, R]); ok {
		err = v.VisitMulExp(node, payload)
		return
	}
	if v, ok := visitor.(VisitorR_MulExp[P, R]); ok {
		result = v.VisitMulExp(node)
		return
	}
	if v, ok := visitor.(VisitorRE_MulExp[P, R]); ok {
		result, err = v.VisitMulExp(node)
		return
	}
	if v, ok := visitor.(VisitorPR_MulExp[P, R]); ok {
		result = v.VisitMulExp(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPRE_MulExp[P, R]); ok {
		result, err = v.VisitMulExp(node, payload)
		return
	}
	ohm.TypeCheckMethod[P, R](visitor, "MulExp")
	return node.DefaultAccept[P, R](visitor, payload)
}

func (node *MulExp) DefaultAccept[P, R any](visitor any, payload P) (result R, err error) {
	switch node.Node.CtorName() {
	case "MulExp":
		return (&MulExp{
			Node: node.Node.Children()[0].(ohm.RuleNode),
		}).DefaultAccept[P, R](visitor, payload)
	case "MulExp_times":
		kids := node.Node.Children()
		_ = kids // only needed in rule.Branch.V is empty
		return (&MulExpTimes{
			MulExp: kids[0].(ohm.RuleNode),
			Term:   kids[1].(ohm.TerminalNode),
			PriExp: kids[2].(ohm.RuleNode),
		}).Accept[P, R](node.Node, visitor, payload)
	case "MulExp_divide":
		kids := node.Node.Children()
		_ = kids // only needed in rule.Branch.V is empty
		return (&MulExpDivide{
			MulExp: kids[0].(ohm.RuleNode),
			Term:   kids[1].(ohm.TerminalNode),
			PriExp: kids[2].(ohm.RuleNode),
		}).Accept[P, R](node.Node, visitor, payload)
	default: // bare case after named ones
		kids := node.Node.Children()
		return (&PriExp{
			Node: kids[0],
		}).Accept[P, R](node.Node, visitor, payload)
	} // end switch
}

// Accept implementation for MulExp_times
//
// MulExp "*" PriExp
func (node *MulExpTimes) Accept[P, R any](this ohm.Node, visitor any, payload P) (result R, err error) {
	ohm.AssertName(this, "MulExp_times")
	if v, ok := visitor.(Visitor_MulExpTimes[P, R]); ok {
		v.VisitMulExpTimes(node)
		return
	}
	if v, ok := visitor.(VisitorE_MulExpTimes[P, R]); ok {
		err = v.VisitMulExpTimes(node)
		return
	}
	if v, ok := visitor.(VisitorP_MulExpTimes[P, R]); ok {
		v.VisitMulExpTimes(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPE_MulExpTimes[P, R]); ok {
		err = v.VisitMulExpTimes(node, payload)
		return
	}
	if v, ok := visitor.(VisitorR_MulExpTimes[P, R]); ok {
		result = v.VisitMulExpTimes(node)
		return
	}
	if v, ok := visitor.(VisitorRE_MulExpTimes[P, R]); ok {
		result, err = v.VisitMulExpTimes(node)
		return
	}
	if v, ok := visitor.(VisitorPR_MulExpTimes[P, R]); ok {
		result = v.VisitMulExpTimes(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPRE_MulExpTimes[P, R]); ok {
		result, err = v.VisitMulExpTimes(node, payload)
		return
	}
	ohm.TypeCheckMethod[P, R](visitor, "MulExpTimes")
	return node.DefaultAccept[P, R](visitor, payload)
}

func (node *MulExpTimes) DefaultAccept[P, R any](visitor any, payload P) (result R, err error) {
	result, err = node.AcceptMulExp[P, R](visitor, payload)
	result, err = node.AcceptTerm[P, R](visitor, payload)
	result, err = node.AcceptPriExp[P, R](visitor, payload)
	return
}

func (node *MulExpTimes) AcceptMulExp[P, R any](visitor any, payload P) (result R, err error) {
	// Rule
	kids := node.MulExp.Children()
	result, err = (&MulExp{
		Node: kids[0],
	}).Accept[P, R](node.MulExp, visitor, payload)
	return
}

func (node *MulExpTimes) AcceptTerm[P, R any](visitor any, payload P) (result R, err error) {
	// Term
	if v, ok := visitor.(ohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *MulExpTimes) AcceptPriExp[P, R any](visitor any, payload P) (result R, err error) {
	// Rule
	kids := node.PriExp.Children()
	result, err = (&PriExp{
		Node: kids[0],
	}).Accept[P, R](node.PriExp, visitor, payload)
	return
}

// Accept implementation for MulExp_divide
//
// MulExp "/" PriExp
func (node *MulExpDivide) Accept[P, R any](this ohm.Node, visitor any, payload P) (result R, err error) {
	ohm.AssertName(this, "MulExp_divide")
	if v, ok := visitor.(Visitor_MulExpDivide[P, R]); ok {
		v.VisitMulExpDivide(node)
		return
	}
	if v, ok := visitor.(VisitorE_MulExpDivide[P, R]); ok {
		err = v.VisitMulExpDivide(node)
		return
	}
	if v, ok := visitor.(VisitorP_MulExpDivide[P, R]); ok {
		v.VisitMulExpDivide(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPE_MulExpDivide[P, R]); ok {
		err = v.VisitMulExpDivide(node, payload)
		return
	}
	if v, ok := visitor.(VisitorR_MulExpDivide[P, R]); ok {
		result = v.VisitMulExpDivide(node)
		return
	}
	if v, ok := visitor.(VisitorRE_MulExpDivide[P, R]); ok {
		result, err = v.VisitMulExpDivide(node)
		return
	}
	if v, ok := visitor.(VisitorPR_MulExpDivide[P, R]); ok {
		result = v.VisitMulExpDivide(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPRE_MulExpDivide[P, R]); ok {
		result, err = v.VisitMulExpDivide(node, payload)
		return
	}
	ohm.TypeCheckMethod[P, R](visitor, "MulExpDivide")
	return node.DefaultAccept[P, R](visitor, payload)
}

func (node *MulExpDivide) DefaultAccept[P, R any](visitor any, payload P) (result R, err error) {
	result, err = node.AcceptMulExp[P, R](visitor, payload)
	result, err = node.AcceptTerm[P, R](visitor, payload)
	result, err = node.AcceptPriExp[P, R](visitor, payload)
	return
}

func (node *MulExpDivide) AcceptMulExp[P, R any](visitor any, payload P) (result R, err error) {
	// Rule
	kids := node.MulExp.Children()
	result, err = (&MulExp{
		Node: kids[0],
	}).Accept[P, R](node.MulExp, visitor, payload)
	return
}

func (node *MulExpDivide) AcceptTerm[P, R any](visitor any, payload P) (result R, err error) {
	// Term
	if v, ok := visitor.(ohm.TerminalVisitor); ok {
		v.Terminal(node.Term)
	}
	return
}

func (node *MulExpDivide) AcceptPriExp[P, R any](visitor any, payload P) (result R, err error) {
	// Rule
	kids := node.PriExp.Children()
	result, err = (&PriExp{
		Node: kids[0],
	}).Accept[P, R](node.PriExp, visitor, payload)
	return
}

// Accept implementation for PriExp
//
// PriExp
// = "(" Exp ")"  -- paren
// | ident
// | number
func (node *PriExp) Accept[P, R any](this ohm.Node, visitor any, payload P) (result R, err error) {
	ohm.AssertName(this, "PriExp")
	if v, ok := visitor.(Visitor_PriExp[P, R]); ok {
		v.VisitPriExp(node)
		return
	}
	if v, ok := visitor.(VisitorE_PriExp[P, R]); ok {
		err = v.VisitPriExp(node)
		return
	}
	if v, ok := visitor.(VisitorP_PriExp[P, R]); ok {
		v.VisitPriExp(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPE_PriExp[P, R]); ok {
		err = v.VisitPriExp(node, payload)
		return
	}
	if v, ok := visitor.(VisitorR_PriExp[P, R]); ok {
		result = v.VisitPriExp(node)
		return
	}
	if v, ok := visitor.(VisitorRE_PriExp[P, R]); ok {
		result, err = v.VisitPriExp(node)
		return
	}
	if v, ok := visitor.(VisitorPR_PriExp[P, R]); ok {
		result = v.VisitPriExp(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPRE_PriExp[P, R]); ok {
		result, err = v.VisitPriExp(node, payload)
		return
	}
	ohm.TypeCheckMethod[P, R](visitor, "PriExp")
	return node.DefaultAccept[P, R](visitor, payload)
}

func (node *PriExp) DefaultAccept[P, R any](visitor any, payload P) (result R, err error) {
	switch node.Node.CtorName() {
	case "PriExp":
		return (&PriExp{
			Node: node.Node.Children()[0].(ohm.RuleNode),
		}).DefaultAccept[P, R](visitor, payload)
	case "PriExp_paren":
		kids := node.Node.Children()
		_ = kids // only needed in rule.Branch.V is empty
		return (&PriExpParen{
			Term1: kids[0].(ohm.TerminalNode),
			Exp:   kids[1].(ohm.RuleNode),
			Term2: kids[2].(ohm.TerminalNode),
		}).Accept[P, R](node.Node, visitor, payload)
	default: // bare case after named ones
		// Rule Node Cases AltUnaryRules
		switch node.Node.CtorName() {
		case "ident":
			kids := node.Node.Children()
			result, err = (&LexIdent{
				Letter: kids[0].(ohm.RuleNode),
				Alnum:  kids[1].(ohm.ListNode),
			}).Accept[P, R](node.Node, visitor, payload)
			return
		case "number":
			kids := node.Node.Children()
			result, err = (&LexNumber{
				Digit: kids[0].(ohm.ListNode),
			}).Accept[P, R](node.Node, visitor, payload)
			return
		default:
			panic("unexpected " + node.Node.CtorName())
		}
	} // end switch
}

// Accept implementation for PriExp_paren
//
// "(" Exp ")"
func (node *PriExpParen) Accept[P, R any](this ohm.Node, visitor any, payload P) (result R, err error) {
	ohm.AssertName(this, "PriExp_paren")
	if v, ok := visitor.(Visitor_PriExpParen[P, R]); ok {
		v.VisitPriExpParen(node)
		return
	}
	if v, ok := visitor.(VisitorE_PriExpParen[P, R]); ok {
		err = v.VisitPriExpParen(node)
		return
	}
	if v, ok := visitor.(VisitorP_PriExpParen[P, R]); ok {
		v.VisitPriExpParen(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPE_PriExpParen[P, R]); ok {
		err = v.VisitPriExpParen(node, payload)
		return
	}
	if v, ok := visitor.(VisitorR_PriExpParen[P, R]); ok {
		result = v.VisitPriExpParen(node)
		return
	}
	if v, ok := visitor.(VisitorRE_PriExpParen[P, R]); ok {
		result, err = v.VisitPriExpParen(node)
		return
	}
	if v, ok := visitor.(VisitorPR_PriExpParen[P, R]); ok {
		result = v.VisitPriExpParen(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPRE_PriExpParen[P, R]); ok {
		result, err = v.VisitPriExpParen(node, payload)
		return
	}
	ohm.TypeCheckMethod[P, R](visitor, "PriExpParen")
	return node.DefaultAccept[P, R](visitor, payload)
}

func (node *PriExpParen) DefaultAccept[P, R any](visitor any, payload P) (result R, err error) {
	result, err = node.AcceptTerm1[P, R](visitor, payload)
	result, err = node.AcceptExp[P, R](visitor, payload)
	result, err = node.AcceptTerm2[P, R](visitor, payload)
	return
}

func (node *PriExpParen) AcceptTerm1[P, R any](visitor any, payload P) (result R, err error) {
	// Term
	if v, ok := visitor.(ohm.TerminalVisitor); ok {
		v.Terminal(node.Term1)
	}
	return
}

func (node *PriExpParen) AcceptExp[P, R any](visitor any, payload P) (result R, err error) {
	// Rule
	kids := node.Exp.Children()
	result, err = (&Exp{
		AddExp: kids[0].(ohm.RuleNode),
	}).Accept[P, R](node.Exp, visitor, payload)
	return
}

func (node *PriExpParen) AcceptTerm2[P, R any](visitor any, payload P) (result R, err error) {
	// Term
	if v, ok := visitor.(ohm.TerminalVisitor); ok {
		v.Terminal(node.Term2)
	}
	return
}

// Accept implementation for ident - an identifier
//
// ident  (an identifier)
// = letter alnum*
func (node *LexIdent) Accept[P, R any](this ohm.Node, visitor any, payload P) (result R, err error) {
	ohm.AssertName(this, "ident")
	if v, ok := visitor.(Visitor_LexIdent[P, R]); ok {
		v.VisitLexIdent(node)
		return
	}
	if v, ok := visitor.(VisitorE_LexIdent[P, R]); ok {
		err = v.VisitLexIdent(node)
		return
	}
	if v, ok := visitor.(VisitorP_LexIdent[P, R]); ok {
		v.VisitLexIdent(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPE_LexIdent[P, R]); ok {
		err = v.VisitLexIdent(node, payload)
		return
	}
	if v, ok := visitor.(VisitorR_LexIdent[P, R]); ok {
		result = v.VisitLexIdent(node)
		return
	}
	if v, ok := visitor.(VisitorRE_LexIdent[P, R]); ok {
		result, err = v.VisitLexIdent(node)
		return
	}
	if v, ok := visitor.(VisitorPR_LexIdent[P, R]); ok {
		result = v.VisitLexIdent(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPRE_LexIdent[P, R]); ok {
		result, err = v.VisitLexIdent(node, payload)
		return
	}
	ohm.TypeCheckMethod[P, R](visitor, "LexIdent")
	return node.DefaultAccept[P, R](visitor, payload)
}

func (node *LexIdent) DefaultAccept[P, R any](visitor any, payload P) (result R, err error) {
	result, err = node.AcceptLetter[P, R](visitor, payload)
	result, err = node.AcceptAlnum[P, R](visitor, payload)
	return
}

func (node *LexIdent) AcceptLetter[P, R any](visitor any, payload P) (result R, err error) {
	// Rule
	// "unknown rule letter"
	if v, ok := visitor.(ohm.NodeVisitor); ok {
		v.NodeVisit(node.Letter)
	} else {
		var (
			fnTerm        func(node ohm.TerminalNode)
			fnSpaceBefore func(spaces string)
		)
		if v, ok := visitor.(ohm.TerminalVisitor); ok {
			fnTerm = v.Terminal
		}
		if v, ok := visitor.(ohm.SpaceBeforeVisitor); ok {
			fnSpaceBefore = v.SpaceBefore
		}
		if fnTerm != nil || fnSpaceBefore != nil {
			ohm.WalkCstCallTermAndSpace(node.Letter, fnTerm, fnSpaceBefore)
		}
	}
	return
}

func (node *LexIdent) AcceptAlnum[P, R any](visitor any, payload P) (result R, err error) {
	for _, n := range node.Alnum.Children() {
		// "unknown rule alnum"
		if v, ok := visitor.(ohm.NodeVisitor); ok {
			v.NodeVisit(n)
		} else {
			var (
				fnTerm        func(node ohm.TerminalNode)
				fnSpaceBefore func(spaces string)
			)
			if v, ok := visitor.(ohm.TerminalVisitor); ok {
				fnTerm = v.Terminal
			}
			if v, ok := visitor.(ohm.SpaceBeforeVisitor); ok {
				fnSpaceBefore = v.SpaceBefore
			}
			if fnTerm != nil || fnSpaceBefore != nil {
				ohm.WalkCstCallTermAndSpace(n, fnTerm, fnSpaceBefore)
			}
		}
	}
	return
}

// Accept implementation for number - a number
//
// number  (a number)
// = digit+
func (node *LexNumber) Accept[P, R any](this ohm.Node, visitor any, payload P) (result R, err error) {
	ohm.AssertName(this, "number")
	if v, ok := visitor.(Visitor_LexNumber[P, R]); ok {
		v.VisitLexNumber(node)
		return
	}
	if v, ok := visitor.(VisitorE_LexNumber[P, R]); ok {
		err = v.VisitLexNumber(node)
		return
	}
	if v, ok := visitor.(VisitorP_LexNumber[P, R]); ok {
		v.VisitLexNumber(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPE_LexNumber[P, R]); ok {
		err = v.VisitLexNumber(node, payload)
		return
	}
	if v, ok := visitor.(VisitorR_LexNumber[P, R]); ok {
		result = v.VisitLexNumber(node)
		return
	}
	if v, ok := visitor.(VisitorRE_LexNumber[P, R]); ok {
		result, err = v.VisitLexNumber(node)
		return
	}
	if v, ok := visitor.(VisitorPR_LexNumber[P, R]); ok {
		result = v.VisitLexNumber(node, payload)
		return
	}
	if v, ok := visitor.(VisitorPRE_LexNumber[P, R]); ok {
		result, err = v.VisitLexNumber(node, payload)
		return
	}
	ohm.TypeCheckMethod[P, R](visitor, "LexNumber")
	return node.DefaultAccept[P, R](visitor, payload)
}

func (node *LexNumber) DefaultAccept[P, R any](visitor any, payload P) (result R, err error) {
	result, err = node.AcceptDigit[P, R](visitor, payload)
	return
}

func (node *LexNumber) AcceptDigit[P, R any](visitor any, payload P) (result R, err error) {
	for _, n := range node.Digit.Children() {
		// "unknown rule digit"
		if v, ok := visitor.(ohm.NodeVisitor); ok {
			v.NodeVisit(n)
		} else {
			var (
				fnTerm        func(node ohm.TerminalNode)
				fnSpaceBefore func(spaces string)
			)
			if v, ok := visitor.(ohm.TerminalVisitor); ok {
				fnTerm = v.Terminal
			}
			if v, ok := visitor.(ohm.SpaceBeforeVisitor); ok {
				fnSpaceBefore = v.SpaceBefore
			}
			if fnTerm != nil || fnSpaceBefore != nil {
				ohm.WalkCstCallTermAndSpace(n, fnTerm, fnSpaceBefore)
			}
		}
	}
	return
}
