// Code generated by ohm-cli generate interfaces. Using gotmpl - DO NOT EDIT.
/* ohm-cli generate go \
--go-type-package arith_visitor \
--generic-methods \
--output-dir arith_visitor
*/
package arith_visitor

// interfaces for grammar Arithmetic

// Exp
// -- rule --
// Exp
// = AddExp
// ----
type Visitor_Exp[P, R any] interface {
	VisitExp(node *Exp)
}
type VisitorE_Exp[P, R any] interface {
	VisitExp(node *Exp) error
}
type VisitorP_Exp[P, R any] interface {
	VisitExp(node *Exp, payload P)
}
type VisitorPE_Exp[P, R any] interface {
	VisitExp(node *Exp, payload P) error
}
type VisitorR_Exp[P, R any] interface {
	VisitExp(node *Exp) (result R)
}
type VisitorRE_Exp[P, R any] interface {
	VisitExp(node *Exp) (result R, err error)
}
type VisitorPR_Exp[P, R any] interface {
	VisitExp(node *Exp, payload P) (result R)
}
type VisitorPRE_Exp[P, R any] interface {
	VisitExp(node *Exp, payload P) (result R, err error)
}

// AddExp
// -- rule --
// AddExp
// = AddExp "+" MulExp  -- plus
// | AddExp "-" MulExp  -- minus
// | MulExp
// ----
type Visitor_AddExp[P, R any] interface {
	VisitAddExp(node *AddExp)
}
type VisitorE_AddExp[P, R any] interface {
	VisitAddExp(node *AddExp) error
}
type VisitorP_AddExp[P, R any] interface {
	VisitAddExp(node *AddExp, payload P)
}
type VisitorPE_AddExp[P, R any] interface {
	VisitAddExp(node *AddExp, payload P) error
}
type VisitorR_AddExp[P, R any] interface {
	VisitAddExp(node *AddExp) (result R)
}
type VisitorRE_AddExp[P, R any] interface {
	VisitAddExp(node *AddExp) (result R, err error)
}
type VisitorPR_AddExp[P, R any] interface {
	VisitAddExp(node *AddExp, payload P) (result R)
}
type VisitorPRE_AddExp[P, R any] interface {
	VisitAddExp(node *AddExp, payload P) (result R, err error)
}

// AddExp_plus
// -- rule --
// AddExp "+" MulExp
// ----
type Visitor_AddExpPlus[P, R any] interface {
	VisitAddExpPlus(node *AddExpPlus)
}
type VisitorE_AddExpPlus[P, R any] interface {
	VisitAddExpPlus(node *AddExpPlus) error
}
type VisitorP_AddExpPlus[P, R any] interface {
	VisitAddExpPlus(node *AddExpPlus, payload P)
}
type VisitorPE_AddExpPlus[P, R any] interface {
	VisitAddExpPlus(node *AddExpPlus, payload P) error
}
type VisitorR_AddExpPlus[P, R any] interface {
	VisitAddExpPlus(node *AddExpPlus) (result R)
}
type VisitorRE_AddExpPlus[P, R any] interface {
	VisitAddExpPlus(node *AddExpPlus) (result R, err error)
}
type VisitorPR_AddExpPlus[P, R any] interface {
	VisitAddExpPlus(node *AddExpPlus, payload P) (result R)
}
type VisitorPRE_AddExpPlus[P, R any] interface {
	VisitAddExpPlus(node *AddExpPlus, payload P) (result R, err error)
}

// AddExp_minus
// -- rule --
// AddExp "-" MulExp
// ----
type Visitor_AddExpMinus[P, R any] interface {
	VisitAddExpMinus(node *AddExpMinus)
}
type VisitorE_AddExpMinus[P, R any] interface {
	VisitAddExpMinus(node *AddExpMinus) error
}
type VisitorP_AddExpMinus[P, R any] interface {
	VisitAddExpMinus(node *AddExpMinus, payload P)
}
type VisitorPE_AddExpMinus[P, R any] interface {
	VisitAddExpMinus(node *AddExpMinus, payload P) error
}
type VisitorR_AddExpMinus[P, R any] interface {
	VisitAddExpMinus(node *AddExpMinus) (result R)
}
type VisitorRE_AddExpMinus[P, R any] interface {
	VisitAddExpMinus(node *AddExpMinus) (result R, err error)
}
type VisitorPR_AddExpMinus[P, R any] interface {
	VisitAddExpMinus(node *AddExpMinus, payload P) (result R)
}
type VisitorPRE_AddExpMinus[P, R any] interface {
	VisitAddExpMinus(node *AddExpMinus, payload P) (result R, err error)
}

// MulExp
// -- rule --
// MulExp
// = MulExp "*" PriExp  -- times
// | MulExp "/" PriExp  -- divide
// | PriExp
// ----
type Visitor_MulExp[P, R any] interface {
	VisitMulExp(node *MulExp)
}
type VisitorE_MulExp[P, R any] interface {
	VisitMulExp(node *MulExp) error
}
type VisitorP_MulExp[P, R any] interface {
	VisitMulExp(node *MulExp, payload P)
}
type VisitorPE_MulExp[P, R any] interface {
	VisitMulExp(node *MulExp, payload P) error
}
type VisitorR_MulExp[P, R any] interface {
	VisitMulExp(node *MulExp) (result R)
}
type VisitorRE_MulExp[P, R any] interface {
	VisitMulExp(node *MulExp) (result R, err error)
}
type VisitorPR_MulExp[P, R any] interface {
	VisitMulExp(node *MulExp, payload P) (result R)
}
type VisitorPRE_MulExp[P, R any] interface {
	VisitMulExp(node *MulExp, payload P) (result R, err error)
}

// MulExp_times
// -- rule --
// MulExp "*" PriExp
// ----
type Visitor_MulExpTimes[P, R any] interface {
	VisitMulExpTimes(node *MulExpTimes)
}
type VisitorE_MulExpTimes[P, R any] interface {
	VisitMulExpTimes(node *MulExpTimes) error
}
type VisitorP_MulExpTimes[P, R any] interface {
	VisitMulExpTimes(node *MulExpTimes, payload P)
}
type VisitorPE_MulExpTimes[P, R any] interface {
	VisitMulExpTimes(node *MulExpTimes, payload P) error
}
type VisitorR_MulExpTimes[P, R any] interface {
	VisitMulExpTimes(node *MulExpTimes) (result R)
}
type VisitorRE_MulExpTimes[P, R any] interface {
	VisitMulExpTimes(node *MulExpTimes) (result R, err error)
}
type VisitorPR_MulExpTimes[P, R any] interface {
	VisitMulExpTimes(node *MulExpTimes, payload P) (result R)
}
type VisitorPRE_MulExpTimes[P, R any] interface {
	VisitMulExpTimes(node *MulExpTimes, payload P) (result R, err error)
}

// MulExp_divide
// -- rule --
// MulExp "/" PriExp
// ----
type Visitor_MulExpDivide[P, R any] interface {
	VisitMulExpDivide(node *MulExpDivide)
}
type VisitorE_MulExpDivide[P, R any] interface {
	VisitMulExpDivide(node *MulExpDivide) error
}
type VisitorP_MulExpDivide[P, R any] interface {
	VisitMulExpDivide(node *MulExpDivide, payload P)
}
type VisitorPE_MulExpDivide[P, R any] interface {
	VisitMulExpDivide(node *MulExpDivide, payload P) error
}
type VisitorR_MulExpDivide[P, R any] interface {
	VisitMulExpDivide(node *MulExpDivide) (result R)
}
type VisitorRE_MulExpDivide[P, R any] interface {
	VisitMulExpDivide(node *MulExpDivide) (result R, err error)
}
type VisitorPR_MulExpDivide[P, R any] interface {
	VisitMulExpDivide(node *MulExpDivide, payload P) (result R)
}
type VisitorPRE_MulExpDivide[P, R any] interface {
	VisitMulExpDivide(node *MulExpDivide, payload P) (result R, err error)
}

// PriExp
// -- rule --
// PriExp
// = "(" Exp ")"  -- paren
// | ident
// | number
// ----
type Visitor_PriExp[P, R any] interface {
	VisitPriExp(node *PriExp)
}
type VisitorE_PriExp[P, R any] interface {
	VisitPriExp(node *PriExp) error
}
type VisitorP_PriExp[P, R any] interface {
	VisitPriExp(node *PriExp, payload P)
}
type VisitorPE_PriExp[P, R any] interface {
	VisitPriExp(node *PriExp, payload P) error
}
type VisitorR_PriExp[P, R any] interface {
	VisitPriExp(node *PriExp) (result R)
}
type VisitorRE_PriExp[P, R any] interface {
	VisitPriExp(node *PriExp) (result R, err error)
}
type VisitorPR_PriExp[P, R any] interface {
	VisitPriExp(node *PriExp, payload P) (result R)
}
type VisitorPRE_PriExp[P, R any] interface {
	VisitPriExp(node *PriExp, payload P) (result R, err error)
}

// PriExp_paren
// -- rule --
// "(" Exp ")"
// ----
type Visitor_PriExpParen[P, R any] interface {
	VisitPriExpParen(node *PriExpParen)
}
type VisitorE_PriExpParen[P, R any] interface {
	VisitPriExpParen(node *PriExpParen) error
}
type VisitorP_PriExpParen[P, R any] interface {
	VisitPriExpParen(node *PriExpParen, payload P)
}
type VisitorPE_PriExpParen[P, R any] interface {
	VisitPriExpParen(node *PriExpParen, payload P) error
}
type VisitorR_PriExpParen[P, R any] interface {
	VisitPriExpParen(node *PriExpParen) (result R)
}
type VisitorRE_PriExpParen[P, R any] interface {
	VisitPriExpParen(node *PriExpParen) (result R, err error)
}
type VisitorPR_PriExpParen[P, R any] interface {
	VisitPriExpParen(node *PriExpParen, payload P) (result R)
}
type VisitorPRE_PriExpParen[P, R any] interface {
	VisitPriExpParen(node *PriExpParen, payload P) (result R, err error)
}

// ident - an identifier
// -- rule --
// ident  (an identifier)
// = letter alnum*
// ----
type Visitor_LexIdent[P, R any] interface {
	VisitLexIdent(node *LexIdent)
}
type VisitorE_LexIdent[P, R any] interface {
	VisitLexIdent(node *LexIdent) error
}
type VisitorP_LexIdent[P, R any] interface {
	VisitLexIdent(node *LexIdent, payload P)
}
type VisitorPE_LexIdent[P, R any] interface {
	VisitLexIdent(node *LexIdent, payload P) error
}
type VisitorR_LexIdent[P, R any] interface {
	VisitLexIdent(node *LexIdent) (result R)
}
type VisitorRE_LexIdent[P, R any] interface {
	VisitLexIdent(node *LexIdent) (result R, err error)
}
type VisitorPR_LexIdent[P, R any] interface {
	VisitLexIdent(node *LexIdent, payload P) (result R)
}
type VisitorPRE_LexIdent[P, R any] interface {
	VisitLexIdent(node *LexIdent, payload P) (result R, err error)
}

// number - a number
// -- rule --
// number  (a number)
// = digit+
// ----
type Visitor_LexNumber[P, R any] interface {
	VisitLexNumber(node *LexNumber)
}
type VisitorE_LexNumber[P, R any] interface {
	VisitLexNumber(node *LexNumber) error
}
type VisitorP_LexNumber[P, R any] interface {
	VisitLexNumber(node *LexNumber, payload P)
}
type VisitorPE_LexNumber[P, R any] interface {
	VisitLexNumber(node *LexNumber, payload P) error
}
type VisitorR_LexNumber[P, R any] interface {
	VisitLexNumber(node *LexNumber) (result R)
}
type VisitorRE_LexNumber[P, R any] interface {
	VisitLexNumber(node *LexNumber) (result R, err error)
}
type VisitorPR_LexNumber[P, R any] interface {
	VisitLexNumber(node *LexNumber, payload P) (result R)
}
type VisitorPRE_LexNumber[P, R any] interface {
	VisitLexNumber(node *LexNumber, payload P) (result R, err error)
}
