// Code generated by ohm-cli generate types. Using gotmpl - DO NOT EDIT.
/* ohm-cli generate go \
--go-type-package arith_visitor \
--generic-methods \
--output-dir arith_visitor
*/
package arith_visitor

import (
	"github.com/ohmjs/ohm-go/ohm"
)

// types for grammar Arithmetic

// Exp
// -- rule --
// Exp
// = AddExp
// ----
type Exp struct {
	AddExp ohm.RuleNode
}

// AddExp
// -- rule --
// AddExp
// = AddExp "+" MulExp  -- plus
// | AddExp "-" MulExp  -- minus
// | MulExp
// ----
type AddExp struct {
	Node ohm.Node
}

// AddExp_plus
// -- rule --
// AddExp "+" MulExp
// ----
type AddExpPlus struct {
	AddExp ohm.RuleNode
	Term   ohm.TerminalNode
	MulExp ohm.RuleNode
}

// AddExp_minus
// -- rule --
// AddExp "-" MulExp
// ----
type AddExpMinus struct {
	AddExp ohm.RuleNode
	Term   ohm.TerminalNode
	MulExp ohm.RuleNode
}

// MulExp
// -- rule --
// MulExp
// = MulExp "*" PriExp  -- times
// | MulExp "/" PriExp  -- divide
// | PriExp
// ----
type MulExp struct {
	Node ohm.Node
}

// MulExp_times
// -- rule --
// MulExp "*" PriExp
// ----
type MulExpTimes struct {
	MulExp ohm.RuleNode
	Term   ohm.TerminalNode
	PriExp ohm.RuleNode
}

// MulExp_divide
// -- rule --
// MulExp "/" PriExp
// ----
type MulExpDivide struct {
	MulExp ohm.RuleNode
	Term   ohm.TerminalNode
	PriExp ohm.RuleNode
}

// PriExp
// -- rule --
// PriExp
// = "(" Exp ")"  -- paren
// | ident
// | number
// ----
type PriExp struct {
	Node ohm.Node
}

// PriExp_paren
// -- rule --
// "(" Exp ")"
// ----
type PriExpParen struct {
	Term1 ohm.TerminalNode
	Exp   ohm.RuleNode
	Term2 ohm.TerminalNode
}

// ident - an identifier
// -- rule --
// ident  (an identifier)
// = letter alnum*
// ----
type LexIdent struct {
	Letter ohm.RuleNode
	Alnum  ohm.ListNode
}

// number - a number
// -- rule --
// number  (a number)
// = digit+
// ----
type LexNumber struct {
	Digit ohm.ListNode
}
